------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PRIOR_ASCVD_HARD_EVENTS_DIAG');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.PRIOR_ASCVD_HARD_EVENTS_DIAG
(
	ALF_PE		BIGINT,
	AGE			INTEGER,
	FIRST_DATE	DATE,
	TYPE		VARCHAR(3),
	CODE		VARCHAR(5),
	CODE_TYPE	VARCHAR(4),
	EVENT_DESC	VARCHAR(120),
	EVENT_DT	DATE,
	EVENT_TYPE	VARCHAR(7)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.PRIOR_ASCVD_HARD_EVENTS_DIAG
--
WITH A AS
(
--IHD - ICD
SELECT
M.ALF_PE,
E.AGE_EPI_STR_YR AS AGE,
M.FIRST_DATE,
M.TYPE,
ICD.DIAG_CD_123 AS CODE,
'ICD' AS CODE_TYPE,
ICD.DIAG_DESC_4 AS EVENT_DESC,
S.ADMIS_DT AS EVENT_DT,
'HE IHD' AS EVENT_TYPE
FROM 
	SAILW1483V.EXTRACT_PEDW_EPISODE E

JOIN SAILW1483V.EXTRACT_PEDW_DIAG D
	ON E.PROV_UNIT_CD = D.PROV_UNIT_CD
	AND E.SPELL_NUM_PE = D.SPELL_NUM_PE
	AND E.EPI_NUM = D.EPI_NUM	
	
JOIN SAILW1483V.PHEN_ASCVD_ICD10 ICD
	ON D.DIAG_CD_123  = ICD.DIAG_CD_123 	
	
JOIN SAILW1483V.EXTRACT_PEDW_SPELL S
	ON E.PROV_UNIT_CD = S.PROV_UNIT_CD 
	AND E.SPELL_NUM_PE = S.SPELL_NUM_PE

JOIN SAILW1483V.COHORT_MASTER_FINAL M
	ON S.ALF_PE = M.ALF_PE
	
WHERE ICD_TYPE = 'IHD'	
AND 
(
DIAG_DESC_4 LIKE('%infarct%')
OR 
DIAG_DESC_4 LIKE('%MI%')
)
AND 
DIAG_DESC_4 NOT LIKE('Old%')
AND 
DIAG_DESC_4 NOT LIKE('%not resulting%')

UNION

--ST - ICD
SELECT
M.ALF_PE,
E.AGE_EPI_STR_YR AS AGE,
M.FIRST_DATE,
M.TYPE,
ICD.DIAG_CD_123 AS CODE,
'ICD' AS CODE_TYPE,
ICD.DIAG_DESC_4 AS EVENT_DESC,
S.ADMIS_DT AS EVENT_DT,
'HE ST' AS EVENT_TYPE
FROM 
	SAILW1483V.EXTRACT_PEDW_EPISODE E

JOIN SAILW1483V.EXTRACT_PEDW_DIAG D
	ON E.PROV_UNIT_CD = D.PROV_UNIT_CD
	AND E.SPELL_NUM_PE = D.SPELL_NUM_PE
	AND E.EPI_NUM = D.EPI_NUM	
	
JOIN SAILW1483V.PHEN_ASCVD_ICD10 ICD
	ON D.DIAG_CD_123  = ICD.DIAG_CD_123 	
	
JOIN SAILW1483V.EXTRACT_PEDW_SPELL S
	ON E.PROV_UNIT_CD = S.PROV_UNIT_CD 
	AND E.SPELL_NUM_PE = S.SPELL_NUM_PE

JOIN SAILW1483V.COHORT_MASTER_FINAL M
	ON S.ALF_PE = M.ALF_PE
	
WHERE ICD_TYPE = 'STROKE'	
AND 
(
DIAG_DESC_4 LIKE('%infarct%')
OR 
DIAG_DESC_4 LIKE('%schaemic%')
OR
DIAG_DESC_4 LIKE('%cclusion%')
)
AND 
DIAG_DESC_4 NOT LIKE('Sequelae%')
AND 
DIAG_DESC_4 NOT LIKE('%ransient%')
	
UNION 

--IHD - READ
SELECT
M.ALF_PE,
M.AGE_DIAG AS AGE,
M.FIRST_DATE,
M.TYPE,
R.READ_CODE AS CODE,
'READ' AS CODE_TYPE,
R.DESC AS EVENT_DESC,
GP.EVENT_DT,
'HE IHD' AS EVENT_TYPE
FROM 
	SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
	
JOIN SAILW1483V.PHEN_ASCVD_READ R
	ON GP.EVENT_CD  = R.READ_CODE 	

JOIN SAILW1483V.COHORT_MASTER_FINAL M
	ON GP.ALF_PE = M.ALF_PE
	
WHERE READ_TYPE = 'IHD'	
AND 
(
DESC LIKE('%infarct%')
OR 
DESC LIKE('%MI%')
)
AND 
DESC NOT LIKE('Old%')
AND 
DESC NOT LIKE('not resulting%')
AND 
DESC NOT LIKE('%H/O%')
AND 
DESC NOT LIKE('%History%')

UNION 

--ST - READ
SELECT
M.ALF_PE,
M.AGE_DIAG AS AGE,
M.FIRST_DATE,
M.TYPE,
R.READ_CODE AS CODE,
'READ' AS CODE_TYPE,
R.DESC AS EVENT_DESC,
GP.EVENT_DT,
'HE ST' AS EVENT_TYPE
FROM 
	SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
	
JOIN SAILW1483V.PHEN_ASCVD_READ R
	ON GP.EVENT_CD  = R.READ_CODE 	

JOIN SAILW1483V.COHORT_MASTER_FINAL M
	ON GP.ALF_PE = M.ALF_PE
	
WHERE READ_TYPE = 'STROKE'	
AND 
(
DESC LIKE('%infarct%')
OR 
DESC LIKE('%troke%')
OR
DESC LIKE('%schaemic%')
OR
DESC LIKE('%cclusion%')
OR 
DESC LIKE('%CVA%')
)
AND 
DESC NOT LIKE('%ransient%')
AND 
DESC NOT LIKE('%H/O%')
AND 
DESC NOT LIKE('not resulting%')
AND
DESC NOT LIKE('%History%')
),


B AS
(
--ST - READ
SELECT
M.ALF_PE,
M.AGE_DIAG AS AGE,
M.FIRST_DATE,
M.TYPE,
R.READ_CODE AS CODE,
'READ' AS CODE_TYPE,
R.DESC AS EVENT_DESC,
GP.EVENT_DT,
'HE ST' AS EVENT_TYPE
FROM 
	SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP
	
JOIN SAILW1483V.PHEN_ASCVD_READ R
	ON GP.EVENT_CD  = R.READ_CODE 	

JOIN SAILW1483V.COHORT_MASTER_FINAL M
	ON GP.ALF_PE = M.ALF_PE
	
WHERE READ_TYPE = 'STROKE'	
AND
DESC LIKE('%ransient%')

UNION

--ST - ICD
SELECT
M.ALF_PE,
E.AGE_EPI_STR_YR AS AGE,
M.FIRST_DATE,
M.TYPE,
ICD.DIAG_CD_123 AS CODE,
'ICD' AS CODE_TYPE,
ICD.DIAG_DESC_4 AS EVENT_DESC,
S.ADMIS_DT AS EVENT_DT,
'HE ST' AS EVENT_TYPE
FROM 
	SAILW1483V.EXTRACT_PEDW_EPISODE E

JOIN SAILW1483V.EXTRACT_PEDW_DIAG D
	ON E.PROV_UNIT_CD = D.PROV_UNIT_CD
	AND E.SPELL_NUM_PE = D.SPELL_NUM_PE
	AND E.EPI_NUM = D.EPI_NUM	
	
JOIN SAILW1483V.PHEN_ASCVD_ICD10 ICD
	ON D.DIAG_CD_123  = ICD.DIAG_CD_123 	
	
JOIN SAILW1483V.EXTRACT_PEDW_SPELL S
	ON E.PROV_UNIT_CD = S.PROV_UNIT_CD 
	AND E.SPELL_NUM_PE = S.SPELL_NUM_PE

JOIN SAILW1483V.COHORT_MASTER_FINAL M
	ON S.ALF_PE = M.ALF_PE
	
WHERE ICD_TYPE = 'STROKE'	
AND
DIAG_DESC_4 LIKE('%ransient%')
)
,

C AS
(
SELECT
A.*
FROM A

UNION

SELECT B.* FROM B

JOIN
(SELECT * FROM A WHERE EVENT_TYPE = 'HE ST')
A
ON B.ALF_PE = A.ALF_PE
AND A.EVENT_DT BETWEEN B.EVENT_DT AND B.EVENT_DT + 90 DAYS
)

SELECT
*
FROM C

ORDER BY ALF_PE, EVENT_DT
; 
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	*
FROM 
	SAILW1483V.PRIOR_ASCVD_HARD_EVENTS_DIAG
ORDER BY ALF_PE, EVENT_DT
	;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.PRIOR_ASCVD_HARD_EVENTS_DIAG;
------------------------------------------