
------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.ALL_DEATH_CAUSE');
COMMIT;
------------------------------------------
--
--Create Table
--
CREATE TABLE SAILW1483V.ALL_DEATH_CAUSE
(
	DEATH_CAUSE_DESC		VARCHAR(60),
	DEATH_CAUSE_CD			VARCHAR(60),
	TOTAL					INTEGER,
	CAUSE_UND				INTEGER,
	CAUSE_1					INTEGER
)
;
COMMIT;
--
------------------------------------------
--
ALTER TABLE SAILW1483V.ALL_DEATH_CAUSE ACTIVATE NOT LOGGED INITIALLY;

INSERT INTO SAILW1483V.ALL_DEATH_CAUSE

SELECT
DEATH_CAUSE_DESC,
DEATH_CAUSE_CD,
COUNT(DEATH_CAUSE_DESC) AS TOTAL,
SUM(CAUSE_UND) AS CAUSE_UND,
SUM(CAUSE_1) AS CAUSE_1
FROM
(
SELECT
I.DESC AS DEATH_CAUSE_DESC,
I.CD AS DEATH_CAUSE_CD,
CASE WHEN I.CD = D.DEATHCAUSE_DIAG_UNDERLYING_CD THEN 1 ELSE 0 END AS CAUSE_UND,
CASE WHEN I.CD = D.DEATHCAUSE_DIAG_1_CD THEN 1 ELSE 0 END AS CAUSE_1
FROM SAIL1483V.ADDE_DEATHS_20230601 D
LEFT JOIN 
(
SELECT
DIAG_CD_4 AS CD,
DIAG_DESC_4 AS DESC
FROM SAILREFRV.ICD10_DIAG_CD_4

UNION

SELECT
DIAG_CD_123 AS CD,
DIAG_DESC_123 AS DESC
FROM SAILREFRV.ICD10_DIAG_CD_123
) I
ON D.DEATHCAUSE_DIAG_UNDERLYING_CD = I.CD
OR D.DEATHCAUSE_DIAG_1_CD = I.CD

WHERE D.DEATH_DT_VALID = 'Valid'
)
GROUP BY DEATH_CAUSE_DESC, DEATH_CAUSE_CD
ORDER BY COUNT(DEATH_CAUSE_DESC) DESC
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT * FROM SAILW1483V.ALL_DEATH_CAUSE;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.ALL_DEATH_CAUSE;
------------------------------------------
