
------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI
(
ALF_PE						BIGINT,	
EVENT_DT					DATE,
EVENT_VAL					DECIMAL(31,8),
WEIGHT						VARCHAR(5)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI

WITH A AS
(
SELECT
ALF_PE,
BMI_DT AS EVENT_DT,
BMI_VAL AS EVENT_VAL,
BMI_CAT AS WEIGHT
FROM SAILW1483V.P4_BMI_CLEAN_ADULTS
)

SELECT
ALF_PE,
EVENT_DT,
CASE WHEN EVENT_VAL > 100 THEN NULL ELSE EVENT_VAL END AS EVENT_VAL,
CASE 
WHEN WEIGHT = 'Normal weight' THEN 'N'
WHEN WEIGHT = 'Overweight' THEN 'OW'
WHEN WEIGHT = 'Underweight' THEN 'UW'
WHEN WEIGHT = 'Obese' THEN 'OB'
ELSE 'UN' END AS WEIGHT
FROM A

WHERE EVENT_VAL IS NOT NULL
;
------------------------------------------

SELECT * FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI;

SELECT COUNT(*) FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI;

SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI;

------------------------------------------


------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI_BASELINE');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI_BASELINE
(
ALF_PE						BIGINT,
FIRST_DATE					DATE,
EVENT_DT					DATE,
EVENT_VAL					DECIMAL(31,8),
WEIGHT						VARCHAR(5)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI_BASELINE

WITH A AS
(
SELECT
B.ALF_PE,
A.DEATH_DT,
EVENT_DT,
EVENT_VAL,
WEIGHT
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI B

JOIN SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS A
ON B.ALF_PE = A.ALF_PE

WHERE B.EVENT_DT <= DEATH_DT
)

SELECT
ALF_PE,
DEATH_DT,
EVENT_DT,
EVENT_VAL,
WEIGHT
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_DT DESC) AS RANK
FROM A
)
WHERE RANK = 1
;
------------------------------------------

SELECT * FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI_BASELINE;

SELECT COUNT(*) FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI_BASELINE;

SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI_BASELINE;

------------------------------------------
