
------------------------------------------   
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER');
COMMIT;
------------------------------------------
--
--Create Table
CREATE TABLE SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER
(
ALF_PE						BIGINT,
TYPE						VARCHAR(15),
GENDER						INTEGER,
WIMD_2019_QUINTILE			INTEGER,
ETHNICITY					VARCHAR(255),
BMI							DECIMAL(31,8),
WEIGHT_CAT					VARCHAR(5),
DEATH_DT					DATE,
AGE_AT_DEATH				INTEGER,
SMOKING_STATUS				CHARACTER(1),
DIABETES_BEFORE				INTEGER,
DEMENTIA_BEFORE				INTEGER,
MALIGNANT_BEFORE			INTEGER,
ASTHMA_BEFORE				INTEGER,
COPD_BEFORE					INTEGER,
RESP_BEFORE					INTEGER,
LIVER_BEFORE				INTEGER,
RENAL_BEFORE				INTEGER,
HF_BEFORE					INTEGER,
AF_BEFORE					INTEGER,
HYPERTENSION_BEFORE			INTEGER
)
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER

WITH PRE AS
(
SELECT
ALF_PE,
MAX(TYPE) AS TYPE,
MAX(GENDER) AS GENDER,
MAX(WIMD_2019_QUINTILE) AS WIMD_2019_QUINTILE,
MAX(ETHNICITY) AS ETHNICITY,
MAX(BMI) AS BMI,
MAX(WEIGHT_CAT) AS WEIGHT_CAT,
MAX(DEATH_DT) AS DEATH_DT,
MAX(AGE_AT_DEATH) AS AGE_AT_DEATH
FROM
(
SELECT
A.ALF_PE,
A.TYPE,
CAST(GP.GNDR_CD AS INTEGER) AS GENDER,
G.WIMD_2019_QUINTILE,
ETH.ETHN_EC_ONS_DATE_LATEST_DESC AS ETHNICITY,
B.EVENT_VAL AS BMI,
B.WEIGHT AS WEIGHT_CAT,
A.DEATH_DT,
(DAYS(A.DEATH_DT) - DAYS(WOB))/365 AS AGE_AT_DEATH
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS A

JOIN (SELECT DISTINCT ALF_PE, WOB, GNDR_CD FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED) GP
ON A.ALF_PE = GP.ALF_PE 

LEFT JOIN SAILW1483V.ETHN_1483 ETH
ON A.ALF_PE = ETH.ALF_PE

LEFT JOIN SAILW1483V.PRIOR_CVD_DEATH_COHORT_BMI_BASELINE B
ON A.ALF_PE = B.ALF_PE

LEFT JOIN SAILW1483V.EXTRACT_P4_WDSD_SINGLE_CLEAN_GEO_CHAR_LSOA2011 G
ON A.ALF_PE = G.ALF_PE AND ((A.DEATH_DT BETWEEN G.START_DATE AND G.END_DATE) OR (A.DEATH_DT <= G.START_DATE AND G.END_DATE IS NULL))
)
GROUP BY ALF_PE
),

B AS
(
SELECT
A.ALF_PE,
A.DEATH_DT,
GP.EVENT_DT,
M.READ_TYPE
FROM PRE A

JOIN SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_MORB_READ M
ON GP.EVENT_CD = M.READ_CODE

WHERE GP.EVENT_DT <= (A.DEATH_DT - 1 YEAR)

ORDER BY A.ALF_PE, GP.EVENT_DT
),

C AS
(
SELECT
ALF_PE,
READ_TYPE
FROM B

GROUP BY ALF_PE,READ_TYPE
ORDER BY ALF_PE
),

D AS
(
SELECT 
ALF_PE,
READ_TYPE,
CASE WHEN READ_TYPE = 'DIABETES' 			THEN 1 ELSE 0 END AS DIABETES_BEFORE,
CASE WHEN READ_TYPE = 'DEMENTIA'			THEN 1 ELSE 0 END AS DEMENTIA_BEFORE,
CASE WHEN READ_TYPE = 'MALIGNANT' 			THEN 1 ELSE 0 END AS MALIGNANT_BEFORE,
CASE WHEN READ_TYPE = 'ASTHMA' 				THEN 1 ELSE 0 END AS ASTHMA_BEFORE,
CASE WHEN READ_TYPE = 'COPD' 				THEN 1 ELSE 0 END AS COPD_BEFORE,
CASE WHEN READ_TYPE IN ('COPD','ASTHMA')	THEN 1 ELSE 0 END AS RESP_BEFORE,
CASE WHEN READ_TYPE = 'LIVER_DISEASE' 		THEN 1 ELSE 0 END AS LIVER_BEFORE,
CASE WHEN READ_TYPE = 'CRF' 				THEN 1 ELSE 0 END AS RENAL_BEFORE,
CASE WHEN READ_TYPE = 'HEART_FAILURE' 		THEN 1 ELSE 0 END AS HF_BEFORE,
CASE WHEN READ_TYPE = 'AF' 					THEN 1 ELSE 0 END AS AF_BEFORE,
CASE WHEN READ_TYPE = 'HYPERTENSION' 		THEN 1 ELSE 0 END AS HYPERTENSION_BEFORE
FROM C
),

E AS
(
SELECT
ALF_PE,
MAX (DIABETES_BEFORE) 		AS DIABETES_BEFORE,
MAX (DEMENTIA_BEFORE) 		AS DEMENTIA_BEFORE,
MAX (MALIGNANT_BEFORE)		AS MALIGNANT_BEFORE,
MAX (ASTHMA_BEFORE) 		AS ASTHMA_BEFORE,
MAX (COPD_BEFORE) 			AS COPD_BEFORE,
MAX (RESP_BEFORE) 			AS RESP_BEFORE,
MAX (LIVER_BEFORE) 			AS LIVER_BEFORE,
MAX (RENAL_BEFORE) 			AS RENAL_BEFORE,
MAX (HF_BEFORE) 			AS HF_BEFORE,
MAX (AF_BEFORE) 			AS AF_BEFORE,
MAX (HYPERTENSION_BEFORE) 	AS HYPERTENSION_BEFORE
FROM D

GROUP BY ALF_PE
ORDER BY ALF_PE
)
,

F AS
(
SELECT
PRE.*,
S.SMOKING_STATUS,
CASE WHEN E.DIABETES_BEFORE IS NULL THEN 0 ELSE E.DIABETES_BEFORE END AS DIABETES_BEFORE,
CASE WHEN E.DEMENTIA_BEFORE IS NULL THEN 0 ELSE E.DEMENTIA_BEFORE END AS DEMENTIA_BEFORE,
CASE WHEN E.MALIGNANT_BEFORE IS NULL THEN 0 ELSE E.MALIGNANT_BEFORE END AS MALIGNANT_BEFORE,
CASE WHEN E.ASTHMA_BEFORE IS NULL THEN 0 ELSE E.ASTHMA_BEFORE END AS ASTHMA_BEFORE,
CASE WHEN E.COPD_BEFORE IS NULL THEN 0 ELSE E.COPD_BEFORE END AS COPD_BEFORE,
CASE WHEN E.RESP_BEFORE IS NULL THEN 0 ELSE E.RESP_BEFORE END AS RESP_BEFORE,
CASE WHEN E.LIVER_BEFORE IS NULL THEN 0 ELSE E.LIVER_BEFORE END AS LIVER_BEFORE,
CASE WHEN E.RENAL_BEFORE IS NULL THEN 0 ELSE E.RENAL_BEFORE END AS RENAL_BEFORE,
CASE WHEN E.HF_BEFORE IS NULL THEN 0 ELSE E.HF_BEFORE END AS HF_BEFORE,
CASE WHEN E.AF_BEFORE IS NULL THEN 0 ELSE E.AF_BEFORE END AS AF_BEFORE,
CASE WHEN E.HYPERTENSION_BEFORE IS NULL THEN 0 ELSE E.HYPERTENSION_BEFORE END AS HYPERTENSION_BEFORE
FROM PRE

LEFT JOIN E
ON PRE.ALF_PE = E.ALF_PE

LEFT JOIN SAILW1483V.P4_SMOKER_OUTPUT S
ON PRE.ALF_PE = S.PATIENT_ID
)

SELECT
F.*
FROM F

LEFT JOIN
(
SELECT
F.ALF_PE
FROM SAILW1483V.COHORT_MASTER_FINAL F 

LEFT JOIN SAILW1483V.PRIOR_MASTER_LLT L
ON F.ALF_PE = L.ALF_PE

WHERE L.ALF_PE IS NULL
) L
ON F.ALF_PE = L.ALF_PE

WHERE L.ALF_PE IS NULL
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER
ORDER BY ALF_PE
FETCH FIRST 100 ROWS ONLY;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER;
--
-- Count distinct alfs
SELECT 
	COUNT(DISTINCT ALF_PE)
FROM 
	SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER;

------------------------------------------   
------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.INC_LLT_PRIOR_CVD_DEATH');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.INC_LLT_PRIOR_CVD_DEATH
(
	ALF_PE			BIGINT,
	DRUG_YR			INTEGER,	
	LLT				VARCHAR(20),
	TYPE			VARCHAR(20),	
	DM_HTN			VARCHAR(20)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.INC_LLT_PRIOR_CVD_DEATH

WITH A AS
(
SELECT
ALF_PE,
DEATH_DT
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER

WHERE YEAR(DEATH_DT) >= 2010
)
,

B AS
(
SELECT
A.ALF_PE,
A.DEATH_DT,
GP.EVENT_DT,
GP.EVENT_VAL,
D.READ_TYPE,
D.READ_CODE
FROM A 

JOIN SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP
ON A.ALF_PE = GP.ALF_PE

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP.EVENT_CD = D.READ_CODE

WHERE GP.EVENT_DT < DEATH_DT
AND GP.EVENT_DT >= DEATH_DT-365

ORDER BY A.ALF_PE, GP.EVENT_DT
)

--SELECT * FROM A
,

D AS 
(
SELECT
	ALF_PE,
	EVENT_DT AS DRUG_DATE,
	YEAR(EVENT_DT) AS DRUG_YR,
	READ_TYPE,
	CASE
		WHEN READ_TYPE = 'HIGH_STATIN' THEN '1'
		ELSE '0'
	END AS HIGH_STATIN,
	CASE
		WHEN READ_TYPE = 'LOW_STATIN' THEN '1'
		ELSE '0'
	END AS LOW_STATIN ,
	CASE
		WHEN (READ_TYPE = 'HIGH_STATIN' OR READ_TYPE = 'LOW_STATIN' ) THEN '1'
		ELSE '0'
	END AS ANY_STATIN,
	CASE
		WHEN READ_TYPE = 'INEGY' THEN '1'
		ELSE '0'
	END AS INEGY,
	CASE
		WHEN READ_TYPE = 'EZETIMIBE' THEN '1'
		ELSE '0'
	END AS EZETIMIBE,
	CASE
		WHEN READ_TYPE = 'FIBRATE' THEN '1'
		ELSE '0'
	END AS FIBRATE,
	CASE
		WHEN READ_TYPE IN ('FIBRATE','EZETIMIBE') THEN '1'
		ELSE '0'
	END AS EZET_FIBR
	,
	CASE
		WHEN READ_CODE IN ('bxi1.','bxi2.','bxkx.','bxkw.','bxk4.','bxk1.',
						  'bxi4.','bxi5.','bxi3.','bxiz.','bxky.','bxkz.',
						  'bxi6.','bxi7.','bxk2.','bxk3.')
		OR READ_CODE LIKE 'bxd%'
		OR READ_CODE LIKE 'bxe%'
		OR READ_CODE LIKE 'bxg%'
		OR READ_CODE LIKE 'bxj%' THEN READ_TYPE
		ELSE NULL
	END AS STATIN_B
FROM B
)

--SELECT * FROM D
--ORDER BY ALF_PE
,

E AS
(
SELECT
ALF_PE,
DRUG_DATE,
DRUG_YR,
CASE WHEN LOW_STATIN = 1 THEN DRUG_DATE ELSE NULL END AS LOW_S_DT,
CASE WHEN HIGH_STATIN = 1 THEN DRUG_DATE ELSE NULL END AS HIGH_S_DT
FROM D
)

--SELECT * FROM E
,

F AS
(
SELECT
ALF_PE,
DRUG_YR,
MIN(LOW_S_DT) AS LOW,
MIN(HIGH_S_DT) AS HIGH
FROM E
GROUP BY ALF_PE,DRUG_YR
ORDER BY ALF_PE,DRUG_YR
)

--SELECT * FROM F
,

G AS
(
SELECT
ALF_PE,
DRUG_YR,
LOW,
HIGH,
CASE 
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) < DAYS(HIGH) THEN LOW
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) >= DAYS(HIGH) THEN HIGH	
	WHEN LOW IS NULL THEN HIGH	
	WHEN HIGH IS NULL THEN LOW
	ELSE NULL
END AS STATIN_FIRST_DT,
CASE 
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) < DAYS(HIGH) THEN 'LOW_STATIN'
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) >= DAYS(HIGH) THEN 'HIGH_STATIN'	
	WHEN LOW IS NULL AND HIGH IS NOT NULL THEN 'HIGH_STATIN'	
	WHEN HIGH IS NULL AND LOW IS NOT NULL THEN 'LOW_STATIN'
	ELSE NULL
END AS STATIN_FIRST
FROM F
)

--SELECT * FROM G
,

H AS
(
SELECT
ALF_PE,
DRUG_YR,
STATIN_FIRST_DT,
STATIN_FIRST
FROM G
)

--SELECT * FROM H
,


I AS 
(
SELECT
	ALF_PE,
	DRUG_YR,
	MAX (HIGH_STATIN) AS HIGH_STATIN,
	MAX (LOW_STATIN) AS LOW_STATIN,
	MAX (ANY_STATIN) AS ANY_STATIN,
	MAX (INEGY) AS INEGY,
	MAX (EZETIMIBE) AS EZETIMIBE,
	MAX (FIBRATE) AS FIBRATE,	
	MAX (EZET_FIBR) AS EZET_FIBR,
	MAX (STATIN_B) AS STATIN_B
FROM D
GROUP BY ALF_PE, DRUG_YR
)

--SELECT * FROM I
,

J AS 
(
SELECT
	*,
	CASE
		WHEN EZET_FIBR = '1' AND STATIN_B IS NOT NULL THEN 'STATIN_COMBI'
		WHEN EZET_FIBR = '0' AND STATIN_B IS NOT NULL THEN STATIN_B	
		WHEN EZET_FIBR = '1' AND STATIN_B IS NULL THEN 'OTHER'
		ELSE STATIN_B
	END AS STATIN_OTHER
FROM I
),

K AS
(
SELECT
	*,
	CASE
		WHEN STATIN_OTHER IS NOT NULL THEN STATIN_OTHER
		ELSE 'NOTX'
	END AS LLT
FROM J
),

L AS
(
SELECT
K.ALF_PE,
K.DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
CASE WHEN (STATIN_B = 'HIGH_STATIN' OR STATIN_B = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE STATIN_B END AS STATIN_B,
CASE WHEN (STATIN_OTHER = 'HIGH_STATIN' OR STATIN_OTHER = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE STATIN_OTHER END AS STATIN_OTHER,	
CASE WHEN (LLT = 'HIGH_STATIN' OR LLT = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE LLT END AS LLT
FROM K

JOIN H
ON K.ALF_PE = H.ALF_PE
AND K.DRUG_YR = H.DRUG_YR
),

M AS
(
SELECT
L.*,
CASE 
	WHEN LLT = 'STATIN_COMBI' THEN 5
	WHEN LLT = 'HIGH_STATIN' THEN 4
	WHEN LLT = 'LOW_STATIN' THEN 3
	WHEN LLT = 'OTHER' THEN 2
	WHEN LLT = 'NOTX' THEN 1	
END AS LLT_RANK
FROM L
),

N AS
(
SELECT
ALF_PE,
DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
STATIN_B,
STATIN_OTHER,	
LLT
FROM M
WHERE NOT EXISTS -- This filter translates to 'fetch all rows from the table where the corresponding field has no larger record'
	(SELECT 
		1 
	FROM M M2 
	WHERE M2.ALF_PE = M.ALF_PE 
	AND M2.LLT_RANK > M.LLT_RANK
	)
),

O AS
(
SELECT
ALF_PE,
DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
STATIN_B,
STATIN_OTHER,	
LLT
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY DRUG_YR) AS RANK
FROM N
)
WHERE RANK = 1
)

SELECT
A.ALF_PE,
YEAR(A.DEATH_DT) AS DRUG_YR,
CASE WHEN O.LLT IS NULL THEN 'NOTX' ELSE O.LLT END AS LLT,
F.TYPE,
CASE 
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 1 THEN 'BOTH'
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 0 THEN 'DM'	
	WHEN F.DIABETES_BEFORE = 0 AND F.HYPERTENSION_BEFORE = 1 THEN 'HTN'
	ELSE 'NONE'
END AS DM_HTN
FROM A

LEFT JOIN O
ON A.ALF_PE = O.ALF_PE

LEFT JOIN SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER F
ON A.ALF_PE = F.ALF_PE
;
----------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT
(
	ALF_PE					BIGINT,
	DEATH_DT				DATE,
	DEATH_YEAR				INTEGER,
	AGE_AT_DEATH			INTEGER,
	GENDER					INTEGER,
	WEIGHT_CAT				VARCHAR(2),
	TYPE					VARCHAR(10),
	SMOKING_STATUS			VARCHAR(1),
	DIABETES_BEFORE			INTEGER,
	DEMENTIA_BEFORE			INTEGER,
	RESP_BEFORE				INTEGER,
	LIVER_BEFORE			INTEGER,
	RENAL_BEFORE			INTEGER,
	AF_BEFORE				INTEGER,	
	HF_BEFORE				INTEGER,
	HYPERTENSION_BEFORE		INTEGER,
	HIGH_RISK				INTEGER,	
	STATIN					INTEGER
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT
--
SELECT
F.ALF_PE,
F.DEATH_DT,
YEAR(F.DEATH_DT) AS DEATH_YEAR,
AGE_AT_DEATH,
GENDER,
WEIGHT_CAT,
L.TYPE,
SMOKING_STATUS,
DIABETES_BEFORE,
DEMENTIA_BEFORE,
RESP_BEFORE,
LIVER_BEFORE,
RENAL_BEFORE,
AF_BEFORE,
HF_BEFORE,
HYPERTENSION_BEFORE,
CASE WHEN HYPERTENSION_BEFORE = 1 OR DIABETES_BEFORE = 1 OR RENAL_BEFORE = 1 THEN 1 ELSE 0 END AS HIGH_RISK,
CASE WHEN L.LLT IN('LOW_STATIN', 'HIGH_STATIN', 'STATIN_COMBI') THEN 1 ELSE 0 END AS STATIN
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER F

JOIN SAILW1483V.INC_LLT_PRIOR_CVD_DEATH L
ON F.ALF_PE = L.ALF_PE

WHERE YEAR(DEATH_DT) >= 2010
;
----------------------------------------------

SELECT * FROM SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT;

SELECT COUNT(*) FROM SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT;

----------------------------------------------