
------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT
(
	ALF_PE					BIGINT,
	EVENT					VARCHAR(10),
	FIRST_DATE				DATE,
	FIRST_YEAR				INTEGER,
	AGE_DIAG				INTEGER,
	GENDER					INTEGER,
	WEIGHT_CAT				VARCHAR(2),
	TYPE					VARCHAR(30),
	SMOKING_STATUS			VARCHAR(1),
	DIABETES_BEFORE			INTEGER,
	DEMENTIA_BEFORE			INTEGER,
	RESP_BEFORE				INTEGER,
	LIVER_BEFORE			INTEGER,
	RENAL_BEFORE			INTEGER,
	RENAL_DIAG				VARCHAR(10),	
	AF_BEFORE				INTEGER,	
	HF_BEFORE				INTEGER,
	HYPERTENSION_BEFORE		INTEGER,
	DIAG_LOC				VARCHAR(10),	
	HIGH_RISK				INTEGER,
	STATIN					INTEGER
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.COMB_COHORT_MASTER_LLT

WITH A AS
(
SELECT
*
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY CAT) AS RANK
FROM
(
SELECT 
'EVENT' AS EVENT,
1 AS CAT,
*
FROM SAILW1483V.PRIOR_MASTER_LLT

UNION

SELECT
'DEATH' AS EVENT,
2 AS CAT,
ALF_PE,
DEATH_DT AS FIRST_DATE,
DEATH_YEAR AS FIRST_YEAR,
AGE_AT_DEATH AS AGE_DIAG,
GENDER,
WEIGHT_CAT,
TYPE,
SMOKING_STATUS,
DIABETES_BEFORE,
DEMENTIA_BEFORE,
RESP_BEFORE,
LIVER_BEFORE,
RENAL_BEFORE,
AF_BEFORE,
HF_BEFORE,
HYPERTENSION_BEFORE,
'DEATH' AS DIAG_LOC,
HIGH_RISK,
STATIN
FROM SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT
)
)
WHERE RANK = 1
)
,

B AS
(
SELECT
ALF_PE,
EVENT,
FIRST_DATE,
FIRST_YEAR,
AGE_DIAG,
GENDER,
WEIGHT_CAT,
CASE 
WHEN EVENT = 'EVENT' AND TYPE = 'IHD' THEN 'Non-fatal - Coronary' 
WHEN EVENT = 'EVENT' AND TYPE = 'ST' THEN 'Non-fatal - Cerebrovascular' 
WHEN EVENT = 'DEATH' AND TYPE = 'IHD' THEN 'Fatal - Coronary' 
WHEN EVENT = 'DEATH' AND TYPE = 'ST' THEN 'Fatal - Cerebrovascular' 
ELSE NULL 
END AS TYPE,
SMOKING_STATUS,
DIABETES_BEFORE,
DEMENTIA_BEFORE,
RESP_BEFORE,
LIVER_BEFORE,
RENAL_BEFORE,
AF_BEFORE,
HF_BEFORE,
HYPERTENSION_BEFORE,
DIAG_LOC,
HIGH_RISK,
STATIN
FROM 
(
SELECT 
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY FIRST_DATE) AS ROW
FROM A
)
WHERE ROW = 1
)
,

GP_EGFR AS
(
SELECT
ALF_PE,
MIN(EVENT_DT) AS EVENT_DT 
FROM
(
SELECT
GP.ALF_PE,
EVENT_DT
FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PRIOR_MASTER_LLT M
ON M.ALF_PE = GP.ALF_PE

JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE (R.PREF_TERM_30 LIKE('%eGFR%') OR R.PREF_TERM_30 LIKE('%Glom%'))
		AND EVENT_DT <= (FIRST_DATE - 1 YEAR)
		AND EVENT_VAL IS NOT NULL
		AND EVENT_VAL > 0	
		AND EVENT_VAL < 60

UNION

SELECT
GP.ALF_PE,
EVENT_DT
FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT M
ON M.ALF_PE = GP.ALF_PE
	
JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE (R.PREF_TERM_30 LIKE('%eGFR%') OR R.PREF_TERM_30 LIKE('%Glom%'))
	AND EVENT_DT <= (DEATH_DT - 1 YEAR)
	AND EVENT_VAL IS NOT NULL
	AND EVENT_VAL > 0
	AND EVENT_VAL < 60
)
GROUP BY ALF_PE
)
,


WRRS_EGFR AS
(
SELECT
ALF_PE,
MIN(TEST) AS EVENT_DT
FROM
(
SELECT
ALF_PE, 
TEST
FROM
(
SELECT
ALF_PE, 
TEST,
SUM(CASE WHEN VAL < 60 THEN 1 ELSE 0 END) OVER(PARTITION BY ALF_PE ORDER BY TEST) AS CKD
FROM
(
SELECT
	W.ALF_PE,
	FIRST_DATE AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL 
	END AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_WRRS_OBSERVATION_RESULT W

JOIN SAILW1483V.PRIOR_MASTER_LLT F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND SPCM_COLLECTED_DT <= (FIRST_DATE - 1 YEAR)
	AND VAL IS NOT NULL
	AND VAL <> ''
	AND CAST(TRIM(VAL) AS INTEGER) IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('*','{redacted}','NA (Haemolysed specimen)','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1',
	'NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13')
)
)
WHERE CKD = 1

UNION 

SELECT
ALF_PE, 
TEST
FROM
(
SELECT
ALF_PE, 
TEST,
SUM(CASE WHEN VAL < 60 THEN 1 ELSE 0 END) OVER(PARTITION BY ALF_PE ORDER BY TEST) AS CKD
FROM
(
SELECT
	W.ALF_PE,
	DEATH_DT AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL 
	END AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAIL1483V.WRRS_OBSERVATION_RESULT_20240605 W

JOIN SAILW1483V.PRIOR_CVD_DEATH_MASTER_LLT F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND SPCM_COLLECTED_DT <= (DEATH_DT - 1 YEAR)
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('*','{redacted}','NA (Haemolysed specimen)','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1',
	'NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13')
)
)
WHERE CKD = 1
)

GROUP BY ALF_PE
)
,

EGFR AS
(
SELECT
ALF_PE,
DIAG
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY PRI ASC) AS RANK
FROM
(
SELECT
ALF_PE,
EVENT_DT,
'READ' AS DIAG,
1 AS PRI
FROM GP_EGFR

UNION

SELECT
ALF_PE,
EVENT_DT,
'PATH' AS DIAG,
2 AS PRI
FROM WRRS_EGFR
)
)
WHERE RANK = 1
)

SELECT
B.ALF_PE,
EVENT,
FIRST_DATE,
FIRST_YEAR,
AGE_DIAG,
GENDER,
WEIGHT_CAT,
TYPE,
SMOKING_STATUS,
DIABETES_BEFORE,
DEMENTIA_BEFORE,
RESP_BEFORE,
LIVER_BEFORE,
RENAL_BEFORE,
CASE WHEN G.ALF_PE IS NULL THEN 'NOT' ELSE G.DIAG END AS RENAL_DIAG,
AF_BEFORE,
HF_BEFORE,
HYPERTENSION_BEFORE,
DIAG_LOC,
CASE WHEN HYPERTENSION_BEFORE = 1 OR DIABETES_BEFORE = 1 OR RENAL_BEFORE = 1 THEN 1 ELSE 0 END AS HIGH_RISK,
STATIN
FROM B

LEFT JOIN EGFR G
ON B.ALF_PE = G.ALF_PE

ORDER BY B.ALF_PE
;
-------------------------------------------------------------------------------------------

SELECT 
* 
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT;

-------------------------------------------------------------------------------------------

--Patients with at least 1 high risk factor

---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PRIOR_COMB_ALF_HIGH_RISK');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.PRIOR_COMB_ALF_HIGH_RISK
(
	ALF_PE					BIGINT,
	FIRST_YEAR				INTEGER,
	TYPE					VARCHAR(30),
	EVENT					VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.PRIOR_COMB_ALF_HIGH_RISK
--
SELECT
ALF_PE,
FIRST_YEAR,
TYPE,
EVENT
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT

WHERE HYPERTENSION_BEFORE = 1 OR DIABETES_BEFORE = 1 OR RENAL_BEFORE = 1
;
COMMIT;
----------------------------------------------

SELECT * FROM SAILW1483V.PRIOR_COMB_ALF_HIGH_RISK;

----------------------------------------------

------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_INC_LLT_PRIOR_COMB');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_INC_LLT_PRIOR_COMB
(
	ALF_PE			BIGINT,
	DRUG_YR			INTEGER,	
	LLT				VARCHAR(20),
	TYPE			VARCHAR(30),
	EVENT			VARCHAR(20),
	DM				INTEGER,
	HTN				INTEGER,
	CKD				INTEGER,	
	MORB			VARCHAR(20),
	RENAL_DIAG		VARCHAR(10),
	DIAG_LOC		VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_INC_LLT_PRIOR_COMB

WITH A AS
(
SELECT
ALF_PE,
FIRST_DATE
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT
)

--SELECT COUNT(DISTINCT ALF_PE) AS COUNT, YEAR(FIRST_DATE) AS YR FROM A GROUP BY YEAR(FIRST_DATE) ORDER BY YEAR(FIRST_DATE)
,

B AS
(
SELECT
A.ALF_PE,
A.FIRST_DATE,
GP.EVENT_DT,
GP.EVENT_VAL,
GP.READ_TYPE,
GP.READ_CODE
FROM A 

JOIN (
SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE, READ_CODE FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP.EVENT_CD = D.READ_CODE

UNION 

SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE, READ_CODE FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP2

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP2.EVENT_CD = D.READ_CODE
) GP
ON A.ALF_PE = GP.ALF_PE

WHERE GP.EVENT_DT < FIRST_DATE
AND GP.EVENT_DT >= FIRST_DATE-365

ORDER BY A.ALF_PE, GP.EVENT_DT
)

--SELECT * FROM A
,

D AS 
(
SELECT
	ALF_PE,
	EVENT_DT AS DRUG_DATE,
	YEAR(EVENT_DT) AS DRUG_YR,
	READ_TYPE,
	CASE
		WHEN READ_TYPE = 'HIGH_STATIN' THEN '1'
		ELSE '0'
	END AS HIGH_STATIN,
	CASE
		WHEN READ_TYPE = 'LOW_STATIN' THEN '1'
		ELSE '0'
	END AS LOW_STATIN ,
	CASE
		WHEN (READ_TYPE = 'HIGH_STATIN' OR READ_TYPE = 'LOW_STATIN' ) THEN '1'
		ELSE '0'
	END AS ANY_STATIN,
	CASE
		WHEN READ_TYPE = 'INEGY' THEN '1'
		ELSE '0'
	END AS INEGY,
	CASE
		WHEN READ_TYPE = 'EZETIMIBE' THEN '1'
		ELSE '0'
	END AS EZETIMIBE,
	CASE
		WHEN READ_TYPE = 'FIBRATE' THEN '1'
		ELSE '0'
	END AS FIBRATE,
	CASE
		WHEN READ_TYPE IN ('FIBRATE','EZETIMIBE') THEN '1'
		ELSE '0'
	END AS EZET_FIBR
	,
	CASE
		WHEN READ_CODE IN ('bxi1.','bxi2.','bxkx.','bxkw.','bxk4.','bxk1.',
						  'bxi4.','bxi5.','bxi3.','bxiz.','bxky.','bxkz.',
						  'bxi6.','bxi7.','bxk2.','bxk3.')
		OR READ_CODE LIKE 'bxd%'
		OR READ_CODE LIKE 'bxe%'
		OR READ_CODE LIKE 'bxg%'
		OR READ_CODE LIKE 'bxj%' THEN READ_TYPE
		ELSE NULL
	END AS STATIN_B
FROM B
)

--SELECT * FROM D
--ORDER BY ALF_PE
,

E AS
(
SELECT
ALF_PE,
DRUG_DATE,
DRUG_YR,
CASE WHEN LOW_STATIN = 1 THEN DRUG_DATE ELSE NULL END AS LOW_S_DT,
CASE WHEN HIGH_STATIN = 1 THEN DRUG_DATE ELSE NULL END AS HIGH_S_DT
FROM D
)

--SELECT * FROM E
,

F AS
(
SELECT
ALF_PE,
DRUG_YR,
MIN(LOW_S_DT) AS LOW,
MIN(HIGH_S_DT) AS HIGH
FROM E
GROUP BY ALF_PE,DRUG_YR
ORDER BY ALF_PE,DRUG_YR
)

--SELECT * FROM F
,

G AS
(
SELECT
ALF_PE,
DRUG_YR,
LOW,
HIGH,
CASE 
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) < DAYS(HIGH) THEN LOW
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) >= DAYS(HIGH) THEN HIGH	
	WHEN LOW IS NULL THEN HIGH	
	WHEN HIGH IS NULL THEN LOW
	ELSE NULL
END AS STATIN_FIRST_DT,
CASE 
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) < DAYS(HIGH) THEN 'LOW_STATIN'
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) >= DAYS(HIGH) THEN 'HIGH_STATIN'	
	WHEN LOW IS NULL AND HIGH IS NOT NULL THEN 'HIGH_STATIN'	
	WHEN HIGH IS NULL AND LOW IS NOT NULL THEN 'LOW_STATIN'
	ELSE NULL
END AS STATIN_FIRST
FROM F
)

--SELECT * FROM G
,

H AS
(
SELECT
ALF_PE,
DRUG_YR,
STATIN_FIRST_DT,
STATIN_FIRST
FROM G
)

--SELECT * FROM H
,


I AS 
(
SELECT
	ALF_PE,
	DRUG_YR,
	MAX (HIGH_STATIN) AS HIGH_STATIN,
	MAX (LOW_STATIN) AS LOW_STATIN,
	MAX (ANY_STATIN) AS ANY_STATIN,
	MAX (INEGY) AS INEGY,
	MAX (EZETIMIBE) AS EZETIMIBE,
	MAX (FIBRATE) AS FIBRATE,	
	MAX (EZET_FIBR) AS EZET_FIBR,
	MAX (STATIN_B) AS STATIN_B
FROM D
GROUP BY ALF_PE, DRUG_YR
)

--SELECT * FROM I
,

J AS 
(
SELECT
	*,
	CASE
		WHEN EZET_FIBR = '1' AND STATIN_B IS NOT NULL THEN 'STATIN_COMBI'
		WHEN EZET_FIBR = '0' AND STATIN_B IS NOT NULL THEN STATIN_B	
		WHEN EZET_FIBR = '1' AND STATIN_B IS NULL THEN 'OTHER'
		ELSE STATIN_B
	END AS STATIN_OTHER
FROM I
),

K AS
(
SELECT
	*,
	CASE
		WHEN STATIN_OTHER IS NOT NULL THEN STATIN_OTHER
		ELSE 'NOTX'
	END AS LLT
FROM J
),

L AS
(
SELECT
K.ALF_PE,
K.DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
CASE WHEN (STATIN_B = 'HIGH_STATIN' OR STATIN_B = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE STATIN_B END AS STATIN_B,
CASE WHEN (STATIN_OTHER = 'HIGH_STATIN' OR STATIN_OTHER = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE STATIN_OTHER END AS STATIN_OTHER,	
CASE WHEN (LLT = 'HIGH_STATIN' OR LLT = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE LLT END AS LLT
FROM K

JOIN H
ON K.ALF_PE = H.ALF_PE
AND K.DRUG_YR = H.DRUG_YR
),

M AS
(
SELECT
L.*,
CASE 
	WHEN LLT = 'STATIN_COMBI' THEN 5
	WHEN LLT = 'HIGH_STATIN' THEN 4
	WHEN LLT = 'LOW_STATIN' THEN 3
	WHEN LLT = 'OTHER' THEN 2
	WHEN LLT = 'NOTX' THEN 1	
END AS LLT_RANK
FROM L
),

N AS
(
SELECT
ALF_PE,
DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
STATIN_B,
STATIN_OTHER,	
LLT
FROM M
WHERE NOT EXISTS -- This filter translates to 'fetch all rows from the table where the corresponding field has no larger record'
	(SELECT 
		1 
	FROM M M2 
	WHERE M2.ALF_PE = M.ALF_PE 
	AND M2.LLT_RANK > M.LLT_RANK
	)
),

O AS
(
SELECT
ALF_PE,
DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
STATIN_B,
STATIN_OTHER,	
LLT
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY DRUG_YR) AS RANK
FROM N
)
WHERE RANK = 1
)

SELECT
A.ALF_PE,
YEAR(A.FIRST_DATE) AS DRUG_YR,
CASE WHEN O.LLT IS NULL THEN 'NOTX' ELSE O.LLT END AS LLT,
F.TYPE,
F.EVENT,
DIABETES_BEFORE AS DM,
HYPERTENSION_BEFORE AS HTN,
RENAL_BEFORE AS CKD,
CASE 
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 1 AND F.RENAL_BEFORE THEN 'MULTI'
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 1 THEN 'MULTI'
	WHEN F.DIABETES_BEFORE = 1 AND F.RENAL_BEFORE = 1 THEN 'MULTI'
	WHEN F.HYPERTENSION_BEFORE = 1 AND F.RENAL_BEFORE = 1 THEN 'MULTI'		
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 0 AND F.RENAL_BEFORE = 0 THEN 'DM'	
	WHEN F.HYPERTENSION_BEFORE = 1 AND F.DIABETES_BEFORE = 0 AND F.RENAL_BEFORE = 0 THEN 'HTN'
	WHEN F.RENAL_BEFORE = 1 AND F.DIABETES_BEFORE = 0 AND F.HYPERTENSION_BEFORE = 0 THEN 'CKD'	
	ELSE 'NONE'
END AS MORB,
RENAL_DIAG,
DIAG_LOC
FROM A

LEFT JOIN O
ON A.ALF_PE = O.ALF_PE

LEFT JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT F
ON A.ALF_PE = F.ALF_PE
;
----------------------------------

--LDL-C prior 1YR

---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB
(
	ALF_PE			BIGINT,
	TYPE			VARCHAR(30),
	DIAG			DATE,
	TEST			DATE,
	MIN_LDL			DECIMAL(5,2),
	STATIN			INTEGER,
	EVENT			VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB
--
WITH A AS
(
SELECT
ALF_PE,
FIRST_DATE,
TYPE,
EVENT,
STATIN
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT
),

B AS
(
SELECT
A.ALF_PE,
A.FIRST_DATE,
A.TYPE,
A.STATIN,
A.EVENT,
GP.EVENT_DT,
GP.EVENT_VAL,
GP.READ_TYPE
FROM A

JOIN (
SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PHEN_LIPID_READ L
ON GP.EVENT_CD = L.READ_CODE

UNION 

SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP2

JOIN SAILW1483V.PHEN_LIPID_READ L
ON GP2.EVENT_CD = L.READ_CODE
) GP
ON A.ALF_PE = GP.ALF_PE

WHERE GP.EVENT_DT < A.FIRST_DATE
AND GP.EVENT_DT >= A.FIRST_DATE-365
AND GP.READ_TYPE = 'LDL'

ORDER BY A.ALF_PE, GP.EVENT_DT
)

--SELECT * FROM B
,

C AS
(
SELECT 
ALF_PE,
TYPE,
STATIN,
EVENT,
FIRST_DATE AS DIAG,
EVENT_DT AS TEST,
EVENT_VAL,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_VAL) AS RANK
FROM B

WHERE EVENT_VAL IS NOT NULL
)

--SELECT * FROM C
SELECT
ALF_PE,
TYPE,
DIAG,
TEST,
EVENT_VAL AS MIN_LDL,
STATIN,
EVENT
FROM
(
SELECT * FROM C WHERE RANK = 1
) F
;
--
SELECT * FROM SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB;
---------------

---------------

--LDL-C prior 3YRS

---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_3YR');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_3YR
(
	ALF_PE			BIGINT,
	TYPE			VARCHAR(30),
	DIAG			DATE,
	TEST			DATE,
	MIN_LDL			DECIMAL(5,2),
	STATIN			INTEGER,
	EVENT			VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_3YR
--
WITH A AS
(
SELECT
ALF_PE,
FIRST_DATE,
TYPE,
EVENT,
STATIN
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT
),

B AS
(
SELECT
A.ALF_PE,
A.FIRST_DATE,
A.TYPE,
A.STATIN,
A.EVENT,
GP.EVENT_DT,
GP.EVENT_VAL,
GP.READ_TYPE
FROM A

JOIN (
SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PHEN_LIPID_READ L
ON GP.EVENT_CD = L.READ_CODE

UNION 

SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP2

JOIN SAILW1483V.PHEN_LIPID_READ L
ON GP2.EVENT_CD = L.READ_CODE
) GP
ON A.ALF_PE = GP.ALF_PE

WHERE GP.EVENT_DT < A.FIRST_DATE
AND GP.EVENT_DT >= A.FIRST_DATE - 3 YEARS
AND GP.READ_TYPE = 'LDL'

ORDER BY A.ALF_PE, GP.EVENT_DT
)

--SELECT * FROM B
,

C AS
(
SELECT 
ALF_PE,
TYPE,
STATIN,
EVENT,
FIRST_DATE AS DIAG,
EVENT_DT AS TEST,
EVENT_VAL,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_VAL) AS RANK
FROM B

WHERE EVENT_VAL IS NOT NULL
)

--SELECT * FROM C
SELECT
ALF_PE,
TYPE,
DIAG,
TEST,
EVENT_VAL AS MIN_LDL,
STATIN,
EVENT
FROM
(
SELECT * FROM C WHERE RANK = 1
) F
;
--
SELECT * FROM SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_3YR;
---------------

---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_MORBS');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_MORBS
(
	ALF_PE			BIGINT,
	FIRST_DATE		DATE,
	TYPE			VARCHAR(30),
	EVENT			VARCHAR(10),	
	DM				INTEGER,
	HTN				INTEGER,
	CKD				INTEGER,
	MORB			VARCHAR(10),
	TEST_CTRL		VARCHAR(12),
	MIN_LDL			DECIMAL(31,8),
	RENAL_DIAG		VARCHAR(10),
	DIAG_LOC		VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_MORBS
--
SELECT
M.ALF_PE,
M.FIRST_DATE,
M.TYPE,
M.EVENT,
DIABETES_BEFORE AS DM,
HYPERTENSION_BEFORE AS HTN,
RENAL_BEFORE AS CKD,
CASE 
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 1 AND M.RENAL_BEFORE THEN 'MULTI'
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 1 THEN 'MULTI'
	WHEN M.DIABETES_BEFORE = 1 AND M.RENAL_BEFORE = 1 THEN 'MULTI'
	WHEN M.HYPERTENSION_BEFORE = 1 AND M.RENAL_BEFORE = 1 THEN 'MULTI'		
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 0 AND M.RENAL_BEFORE = 0 THEN 'DM'	
	WHEN M.HYPERTENSION_BEFORE = 1 AND M.DIABETES_BEFORE = 0 AND M.RENAL_BEFORE = 0 THEN 'HTN'
	WHEN M.RENAL_BEFORE = 1 AND M.DIABETES_BEFORE = 0 AND M.HYPERTENSION_BEFORE = 0 THEN 'CKD'	
	ELSE 'NONE'
END AS MORB,
CASE 
	WHEN L.ALF_PE IS NOT NULL AND MIN_LDL < 1.8 THEN '<1.8'
	WHEN L.ALF_PE IS NOT NULL AND MIN_LDL >= 1.8 AND MIN_LDL <  2.6 THEN '1.8 to <2.6'
	WHEN L.ALF_PE IS NOT NULL AND MIN_LDL >= 2.6 THEN '>= 2.6' 
	ELSE 'NOT' 
END AS TEST_CTRL,
MIN_LDL,
RENAL_DIAG,
DIAG_LOC
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

LEFT JOIN SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB L
ON M.ALF_PE = L.ALF_PE

;
--
SELECT * FROM SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_MORBS;
---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_LLT');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_LLT
(
	ALF_PE			BIGINT,
	DRUG_YR			INTEGER,
	LLT				VARCHAR(20),	
	TYPE			VARCHAR(30),
	EVENT			VARCHAR(10),
	DM				INTEGER,
	HTN				INTEGER,
	CKD				INTEGER,	
	TEST_CTRL		VARCHAR(12),
	MORB			VARCHAR(10),
	RENAL_DIAG		VARCHAR(10),
	DIAG_LOC		VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_LLT
--
WITH A AS
(
SELECT 
*,
CASE 
	WHEN MIN_LDL < 1.8 THEN '<1.8'
	WHEN MIN_LDL >= 1.8 AND MIN_LDL <  2.6 THEN '1.8 to <2.6'
	WHEN MIN_LDL >= 2.6 THEN '>= 2.6' 
END AS TEST_CTRL
FROM SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB
)
,

B AS
(
SELECT
A.ALF_PE,
A.TEST,
A.DIAG,
GP.EVENT_DT,
GP.EVENT_VAL,
GP.READ_TYPE,
GP.READ_CODE
FROM A 

JOIN (
SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE, READ_CODE FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP.EVENT_CD = D.READ_CODE

UNION 

SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE, READ_CODE FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP2

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP2.EVENT_CD = D.READ_CODE
) GP
ON A.ALF_PE = GP.ALF_PE

WHERE GP.EVENT_DT >= TEST
AND GP.EVENT_DT < DIAG

ORDER BY A.ALF_PE, GP.EVENT_DT
)

--SELECT * FROM B
,

D AS 
(
SELECT
	ALF_PE,
	EVENT_DT AS DRUG_DATE,
	YEAR(EVENT_DT) AS DRUG_YR,
	READ_TYPE,
	CASE
		WHEN READ_TYPE = 'HIGH_STATIN' THEN '1'
		ELSE '0'
	END AS HIGH_STATIN,
	CASE
		WHEN READ_TYPE = 'LOW_STATIN' THEN '1'
		ELSE '0'
	END AS LOW_STATIN ,
	CASE
		WHEN (READ_TYPE = 'HIGH_STATIN' OR READ_TYPE = 'LOW_STATIN' ) THEN '1'
		ELSE '0'
	END AS ANY_STATIN,
	CASE
		WHEN READ_TYPE = 'INEGY' THEN '1'
		ELSE '0'
	END AS INEGY,
	CASE
		WHEN READ_TYPE = 'EZETIMIBE' THEN '1'
		ELSE '0'
	END AS EZETIMIBE,
	CASE
		WHEN READ_TYPE = 'FIBRATE' THEN '1'
		ELSE '0'
	END AS FIBRATE,
	CASE
		WHEN READ_TYPE IN ('FIBRATE','EZETIMIBE') THEN '1'
		ELSE '0'
	END AS EZET_FIBR
	,
	CASE
		WHEN READ_CODE IN ('bxi1.','bxi2.','bxkx.','bxkw.','bxk4.','bxk1.',
						  'bxi4.','bxi5.','bxi3.','bxiz.','bxky.','bxkz.',
						  'bxi6.','bxi7.','bxk2.','bxk3.')
		OR READ_CODE LIKE 'bxd%'
		OR READ_CODE LIKE 'bxe%'
		OR READ_CODE LIKE 'bxg%'
		OR READ_CODE LIKE 'bxj%' THEN READ_TYPE
		ELSE NULL
	END AS STATIN_B
FROM B
)

--SELECT * FROM D
--ORDER BY ALF_PE
,

E AS
(
SELECT
ALF_PE,
DRUG_DATE,
DRUG_YR,
CASE WHEN LOW_STATIN = 1 THEN DRUG_DATE ELSE NULL END AS LOW_S_DT,
CASE WHEN HIGH_STATIN = 1 THEN DRUG_DATE ELSE NULL END AS HIGH_S_DT
FROM D
)

--SELECT * FROM E
,

F AS
(
SELECT
ALF_PE,
DRUG_YR,
MIN(LOW_S_DT) AS LOW,
MIN(HIGH_S_DT) AS HIGH
FROM E
GROUP BY ALF_PE,DRUG_YR
ORDER BY ALF_PE,DRUG_YR
)

--SELECT * FROM F
,

G AS
(
SELECT
ALF_PE,
DRUG_YR,
LOW,
HIGH,
CASE 
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) < DAYS(HIGH) THEN LOW
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) >= DAYS(HIGH) THEN HIGH	
	WHEN LOW IS NULL THEN HIGH	
	WHEN HIGH IS NULL THEN LOW
	ELSE NULL
END AS STATIN_FIRST_DT,
CASE 
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) < DAYS(HIGH) THEN 'LOW_STATIN'
	WHEN LOW IS NOT NULL AND HIGH IS NOT NULL AND DAYS(LOW) >= DAYS(HIGH) THEN 'HIGH_STATIN'	
	WHEN LOW IS NULL AND HIGH IS NOT NULL THEN 'HIGH_STATIN'	
	WHEN HIGH IS NULL AND LOW IS NOT NULL THEN 'LOW_STATIN'
	ELSE NULL
END AS STATIN_FIRST
FROM F
)

--SELECT * FROM G
,

H AS
(
SELECT
ALF_PE,
DRUG_YR,
STATIN_FIRST_DT,
STATIN_FIRST
FROM G
)

--SELECT * FROM H
,


I AS 
(
SELECT
	ALF_PE,
	DRUG_YR,
	MAX (HIGH_STATIN) AS HIGH_STATIN,
	MAX (LOW_STATIN) AS LOW_STATIN,
	MAX (ANY_STATIN) AS ANY_STATIN,
	MAX (INEGY) AS INEGY,
	MAX (EZETIMIBE) AS EZETIMIBE,
	MAX (FIBRATE) AS FIBRATE,	
	MAX (EZET_FIBR) AS EZET_FIBR,
	MAX (STATIN_B) AS STATIN_B
FROM D
GROUP BY ALF_PE, DRUG_YR
)

--SELECT * FROM I
,

J AS 
(
SELECT
	*,
	CASE
		WHEN EZET_FIBR = '1' AND STATIN_B IS NOT NULL THEN 'STATIN_COMBI'
		WHEN EZET_FIBR = '0' AND STATIN_B IS NOT NULL THEN STATIN_B	
		WHEN EZET_FIBR = '1' AND STATIN_B IS NULL THEN 'OTHER'
		ELSE STATIN_B
	END AS STATIN_OTHER
FROM I
),

K AS
(
SELECT
	*,
	CASE
		WHEN STATIN_OTHER IS NOT NULL THEN STATIN_OTHER
		ELSE 'NOTX'
	END AS LLT
FROM J
),

L AS
(
SELECT
K.ALF_PE,
K.DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
CASE WHEN (STATIN_B = 'HIGH_STATIN' OR STATIN_B = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE STATIN_B END AS STATIN_B,
CASE WHEN (STATIN_OTHER = 'HIGH_STATIN' OR STATIN_OTHER = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE STATIN_OTHER END AS STATIN_OTHER,	
CASE WHEN (LLT = 'HIGH_STATIN' OR LLT = 'LOW_STATIN') THEN H.STATIN_FIRST ELSE LLT END AS LLT
FROM K

JOIN H
ON K.ALF_PE = H.ALF_PE
AND K.DRUG_YR = H.DRUG_YR
),

M AS
(
SELECT
L.*,
CASE 
	WHEN LLT = 'STATIN_COMBI' THEN 5
	WHEN LLT = 'HIGH_STATIN' THEN 4
	WHEN LLT = 'LOW_STATIN' THEN 3
	WHEN LLT = 'OTHER' THEN 2
	WHEN LLT = 'NOTX' THEN 1	
END AS LLT_RANK
FROM L
),

N AS
(
SELECT
ALF_PE,
DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
STATIN_B,
STATIN_OTHER,	
LLT
FROM M
WHERE NOT EXISTS -- This filter translates to 'fetch all rows from the table where the corresponding field has no larger record'
	(SELECT 
		1 
	FROM M M2 
	WHERE M2.ALF_PE = M.ALF_PE 
	AND M2.LLT_RANK > M.LLT_RANK
	)
),

O AS
(
SELECT
ALF_PE,
DRUG_YR,
HIGH_STATIN,
LOW_STATIN,
ANY_STATIN,
INEGY,
EZETIMIBE,
FIBRATE,	
EZET_FIBR,
STATIN_B,
STATIN_OTHER,	
LLT
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY DRUG_YR) AS RANK
FROM N
)
WHERE RANK = 1
)

SELECT
A.ALF_PE,
YEAR(F.FIRST_DATE) AS DRUG_YR,
CASE WHEN O.LLT IS NULL THEN 'NOTX' ELSE O.LLT END AS LLT,
F.TYPE,
F.EVENT,
DIABETES_BEFORE AS DM,
HYPERTENSION_BEFORE AS HTN,
RENAL_BEFORE AS CKD,
A.TEST_CTRL,
CASE 
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 1 AND F.RENAL_BEFORE THEN 'MULTI'
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 1 THEN 'MULTI'
	WHEN F.DIABETES_BEFORE = 1 AND F.RENAL_BEFORE = 1 THEN 'MULTI'
	WHEN F.HYPERTENSION_BEFORE = 1 AND F.RENAL_BEFORE = 1 THEN 'MULTI'		
	WHEN F.DIABETES_BEFORE = 1 AND F.HYPERTENSION_BEFORE = 0 AND F.RENAL_BEFORE = 0 THEN 'DM'	
	WHEN F.HYPERTENSION_BEFORE = 1 AND F.DIABETES_BEFORE = 0 AND F.RENAL_BEFORE = 0 THEN 'HTN'
	WHEN F.RENAL_BEFORE = 1 AND F.DIABETES_BEFORE = 0 AND F.HYPERTENSION_BEFORE = 0 THEN 'CKD'	
	ELSE 'NONE'
END AS MORB,
RENAL_DIAG,
DIAG_LOC
FROM A

LEFT JOIN O
ON A.ALF_PE = O.ALF_PE

LEFT JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT F
ON A.ALF_PE = F.ALF_PE
;
---------------
SELECT * FROM SAILW1483V.TEMP_LDL_CONTROL_PRIOR_COMB_LLT;
---------------

---------------

--Blood pressure prior 1YR

---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_BP_PRIOR_COMB');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_BP_PRIOR_COMB
(
	ALF_PE			BIGINT,
	TYPE			VARCHAR(30),
	EVENT			VARCHAR(10),
	STATIN			INTEGER,
	DIAG			DATE,
	TEST			DATE,
	SYS				INTEGER,
	DYS				INTEGER	
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_BP_PRIOR_COMB
--
WITH A AS
(
SELECT
ALF_PE,
FIRST_DATE,
TYPE,
EVENT,
STATIN
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT


),

B AS
(
SELECT
A.ALF_PE,
A.FIRST_DATE,
A.TYPE,
A.EVENT,
A.STATIN,
BP.EVENT_DT,
SYS,
DYS
FROM A

JOIN SAILW1483V.ALL_CLEANED_BLOOD_PRESSURES BP
ON A.ALF_PE = BP.ALF_PE

WHERE BP.EVENT_DT < A.FIRST_DATE
AND BP.EVENT_DT >= A.FIRST_DATE-365

ORDER BY A.ALF_PE, BP.EVENT_DT
)

--SELECT * FROM B
,

C AS
(
SELECT 
ALF_PE,
TYPE,
EVENT,
STATIN,
FIRST_DATE AS DIAG,
EVENT_DT AS TEST,
SYS,
DYS,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_DT DESC) AS RANK
FROM B

WHERE SYS IS NOT NULL
AND DYS IS NOT NULL
)

--SELECT * FROM C

SELECT
ALF_PE,
TYPE,
EVENT,
STATIN,
DIAG,
TEST,
SYS,
DYS
FROM
(
SELECT * FROM C WHERE RANK = 1
) 
;
--
SELECT * FROM SAILW1483V.TEMP_BP_PRIOR_COMB;

---------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_BP_CONTROL_PRIOR_COMB_MORBS');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_BP_CONTROL_PRIOR_COMB_MORBS
(
	ALF_PE			BIGINT,
	FIRST_DATE		DATE,
	TYPE			VARCHAR(30),
	EVENT			VARCHAR(10),
	DM				INTEGER,
	HTN				INTEGER,
	CKD				INTEGER,	
	MORB			VARCHAR(10),
	SYS				INTEGER,
	DYS				INTEGER,
	TEST_CTRL		VARCHAR(12),
	RENAL_DIAG		VARCHAR(10),
	DIAG_LOC		VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_BP_CONTROL_PRIOR_COMB_MORBS
--
SELECT
M.ALF_PE,
M.FIRST_DATE,
M.TYPE,
M.EVENT,
DIABETES_BEFORE AS DM,
HYPERTENSION_BEFORE AS HTN,
RENAL_BEFORE AS CKD,
CASE 
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 1 AND M.RENAL_BEFORE THEN 'MULTI'
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 1 THEN 'MULTI'
	WHEN M.DIABETES_BEFORE = 1 AND M.RENAL_BEFORE = 1 THEN 'MULTI'
	WHEN M.HYPERTENSION_BEFORE = 1 AND M.RENAL_BEFORE = 1 THEN 'MULTI'		
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 0 AND M.RENAL_BEFORE = 0 THEN 'DM'	
	WHEN M.HYPERTENSION_BEFORE = 1 AND M.DIABETES_BEFORE = 0 AND M.RENAL_BEFORE = 0 THEN 'HTN'
	WHEN M.RENAL_BEFORE = 1 AND M.DIABETES_BEFORE = 0 AND M.HYPERTENSION_BEFORE = 0 THEN 'CKD'	
	ELSE 'NONE'
END AS MORB,
SYS,
DYS,
CASE 
	WHEN L.ALF_PE IS NOT NULL AND (SYS >= 140 OR DYS >= 90) THEN 'TEST'
	WHEN L.ALF_PE IS NOT NULL THEN 'CTRL' 
	ELSE 'NOT' 
END AS TEST_CTRL,
RENAL_DIAG,
DIAG_LOC
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

LEFT JOIN SAILW1483V.TEMP_BP_PRIOR_COMB L
ON M.ALF_PE = L.ALF_PE

;
--
SELECT * FROM SAILW1483V.TEMP_BP_CONTROL_PRIOR_COMB_MORBS;
----------------------------------------------

--QRISK PRIOR_COMB 1 YR

------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_QRISK_PRIOR_COMB');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_QRISK_PRIOR_COMB
(
	ALF_PE			BIGINT,
	FIRST_DATE		DATE,
	EVENT_DT		DATE,	
	EVENT_CD		VARCHAR(10),
	EVENT_VAL		DECIMAL(31,8),
	DESC			VARCHAR(60)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_QRISK_PRIOR_COMB

WITH A AS
(
SELECT
ALF_PE,
FIRST_DATE
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT


),

B AS
(
SELECT
A.ALF_PE,
A.FIRST_DATE,
GP.EVENT_DT,
GP.EVENT_CD,
GP.EVENT_VAL,
CASE
	WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
	WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
	ELSE PREF_TERM_198
END AS DESC
FROM A 

JOIN (
SELECT ALF_PE, EVENT_DT, EVENT_CD, EVENT_VAL FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

WHERE GP.EVENT_CD IN('38DP.','38DF.')

UNION 

SELECT ALF_PE, EVENT_DT, EVENT_CD, EVENT_VAL FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP2

WHERE GP2.EVENT_CD IN('38DP.','38DF.')
) GP
ON A.ALF_PE = GP.ALF_PE

LEFT JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE GP.EVENT_DT < FIRST_DATE
AND GP.EVENT_DT >= FIRST_DATE-(365 * 5)
AND EVENT_VAL IS NOT NULL
)

--SELECT * FROM B

SELECT
	ALF_PE,
	FIRST_DATE,
	EVENT_DT,	
	EVENT_CD,
	ROUND(EVENT_VAL,0) AS EVENT_VAL,
	DESC
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE, EVENT_DT ORDER BY EVENT_DT) AS RANK
FROM B
) 

WHERE RANK = 1
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.TEMP_QRISK_PRIOR_COMB;

SELECT 
COUNT(DISTINCT ALF_PE) 
FROM SAILW1483V.TEMP_QRISK_PRIOR_COMB;

----------------------------------------

------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_QRISK_INVALID');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_QRISK_INVALID
(
	ALF_PE			BIGINT,
	QRISK_DT		DATE,
	QRISK_VAL		DECIMAL(31,8)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.TEMP_QRISK_INVALID
SELECT 
ALF_PE,
QRISK_DT,
MAX(QRISK_VAL) AS QRISK_VAL
FROM
(
SELECT
A.ALF_PE,
A.EVENT_DT AS QRISK_DT,
GP.EVENT_DT AS STATIN_DT,
A.EVENT_VAL AS QRISK_VAL,
GP.READ_TYPE
FROM SAILW1483V.TEMP_QRISK_PRIOR_COMB A

JOIN (
SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP.EVENT_CD = D.READ_CODE

UNION 

SELECT ALF_PE, EVENT_DT, EVENT_VAL, READ_TYPE FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP2

JOIN SAILW1483V.PHEN_DRUG_READ D
ON GP2.EVENT_CD = D.READ_CODE
) GP
ON A.ALF_PE = GP.ALF_PE

WHERE GP.EVENT_DT < A.EVENT_DT
AND READ_TYPE IN('LOW_STATIN','HIGH_STATIN')
ORDER BY A.ALF_PE, GP.EVENT_DT
)
GROUP BY ALF_PE, QRISK_DT
ORDER BY ALF_PE, QRISK_DT
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.TEMP_QRISK_INVALID;

SELECT 
COUNT(DISTINCT ALF_PE) 
FROM SAILW1483V.TEMP_QRISK_INVALID;

------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_QRISK_PRIOR_COMB_MAX');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_QRISK_PRIOR_COMB_MAX
(
	ALF_PE				BIGINT,
	TYPE				VARCHAR(30),
	EVENT				VARCHAR(10),	
	FIRST_DATE			DATE,
	YR					INTEGER,
    QRISK_VAL			VARCHAR(20),
	DM					INTEGER,
	HTN					INTEGER,
	CKD					INTEGER,
	MORB				VARCHAR(20),
	RENAL_DIAG			VARCHAR(10),
	DIAG_LOC			VARCHAR(10)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
ALTER TABLE SAILW1483V.TEMP_QRISK_PRIOR_COMB_MAX ACTIVATE NOT LOGGED INITIALLY;

INSERT INTO SAILW1483V.TEMP_QRISK_PRIOR_COMB_MAX

WITH X AS
(
SELECT
	X.ALF_PE,
	X.TYPE,
	X.EVENT,
	X.FIRST_DATE,
	Q.EVENT_DT AS QRISK_DT,
	Q.EVENT_VAL AS QRISK_VAL
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT X

LEFT JOIN SAILW1483V.TEMP_QRISK_PRIOR_COMB Q
ON X.ALF_PE = Q.ALF_PE

LEFT JOIN 
(SELECT * FROM SAILW1483V.TEMP_INC_LLT_PRIOR_COMB WHERE LLT <> 'NOTX') L
ON X.ALF_PE = L.ALF_PE

WHERE 
EVENT_VAL IS NOT NULL
AND L.ALF_PE IS NULL
AND AGE_DIAG < 85
AND RENAL_BEFORE = 0
)
--SELECT COUNT(DISTINCT ALF_PE) FROM X
,

B AS
(
SELECT
ALF_PE,
TYPE,
FIRST_DATE,
QRISK_DT,
QRISK_VAL
FROM 
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY QRISK_VAL DESC) AS RANK
FROM X
)
WHERE RANK = 1
)

SELECT
M.ALF_PE,
M.TYPE,
M.EVENT,
M.FIRST_DATE,
YEAR(M.FIRST_DATE) AS YR,
CASE 
	WHEN B.QRISK_VAL < 10 THEN '<10' 
	WHEN B.QRISK_VAL BETWEEN 10 AND 19 THEN '10-19'
	WHEN B.QRISK_VAL >= 20 THEN '>20'
	ELSE 'NOT'
END AS QRISK_VAL,
DIABETES_BEFORE AS DM,
HYPERTENSION_BEFORE AS HTN,
RENAL_BEFORE AS CKD,
CASE 
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 1 AND M.RENAL_BEFORE THEN 'MULTI'
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 1 THEN 'MULTI'
	WHEN M.DIABETES_BEFORE = 1 AND M.RENAL_BEFORE = 1 THEN 'MULTI'
	WHEN M.HYPERTENSION_BEFORE = 1 AND M.RENAL_BEFORE = 1 THEN 'MULTI'		
	WHEN M.DIABETES_BEFORE = 1 AND M.HYPERTENSION_BEFORE = 0 AND M.RENAL_BEFORE = 0 THEN 'DM'	
	WHEN M.HYPERTENSION_BEFORE = 1 AND M.DIABETES_BEFORE = 0 AND M.RENAL_BEFORE = 0 THEN 'HTN'
	WHEN M.RENAL_BEFORE = 1 AND M.DIABETES_BEFORE = 0 AND M.HYPERTENSION_BEFORE = 0 THEN 'CKD'	
	ELSE 'NONE'
END AS MORB,
M.RENAL_DIAG,
M.DIAG_LOC
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

LEFT JOIN B
ON B.ALF_PE = M.ALF_PE

LEFT JOIN 
(SELECT * FROM SAILW1483V.TEMP_INC_LLT_PRIOR_COMB WHERE LLT <> 'NOTX') L
ON M.ALF_PE = L.ALF_PE

WHERE M.AGE_DIAG < 85
AND M.RENAL_BEFORE = 0
--AND YEAR(M.FIRST_DATE) >= 2014
AND L.ALF_PE IS NULL
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.TEMP_QRISK_PRIOR_COMB_MAX;

SELECT 
COUNT(DISTINCT ALF_PE) 
FROM SAILW1483V.TEMP_QRISK_PRIOR_COMB_MAX
;

-----------------------------------------------------------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_RISK_READINGS_3YR');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_RISK_READINGS_3YR
(
	ALF_PE		BIGINT,
	FIRST_DATE	DATE,
	TYPE		VARCHAR(5),
	HIGH		INTEGER
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table

INSERT INTO SAILW1483V.TEMP_RISK_READINGS_3YR

WITH GP_DATA AS
(
SELECT
GP.*
FROM SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M
ON M.ALF_PE = GP.ALF_PE

JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE HIGH_RISK = 0
AND EVENT_DT < (FIRST_DATE - 1 YEAR)
AND (EVENT_CD LIKE('42W%') OR (R.PREF_TERM_30 LIKE('%eGFR%') OR R.PREF_TERM_30 LIKE('%Glom%')))
AND EVENT_VAL > 0
		
UNION

SELECT
GP.*
FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M
ON M.ALF_PE = GP.ALF_PE

JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE HIGH_RISK = 0
AND EVENT_DT < (FIRST_DATE - 1 YEAR)	
AND (EVENT_CD LIKE('42W%') OR (R.PREF_TERM_30 LIKE('%eGFR%') OR R.PREF_TERM_30 LIKE('%Glom%')))
AND EVENT_VAL > 0
)
,

HBA1C_READ AS
(
SELECT
ALF_PE,
FIRST_DATE,
EVENT_VAL,
NULL AS EVENT_VAL_2,
'HbA1c' AS TYPE
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_VAL DESC) AS RANK
FROM
(
SELECT
	M.ALF_PE,
	FIRST_DATE,	
	EVENT_CD,
	EVENT_DT,
	EVENT_VAL,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC		
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

JOIN GP_DATA GP
ON M.ALF_PE = GP.ALF_PE

LEFT JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE
	
WHERE 
	(GP.EVENT_DT BETWEEN M.FIRST_DATE - 4 YEARS AND (M.FIRST_DATE - 1 YEAR))
	AND EVENT_CD LIKE('42W%')
	AND EVENT_VAL IS NOT NULL
)
)
WHERE RANK = 1
),

WRRS_HBA1C AS
(
SELECT
	W.ALF_PE,
	FIRST_DATE AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(VAL AS DECIMAL(31,8)) AS EVENT_VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_WRRS_OBSERVATION_RESULT W

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('HbA1c%')
	AND (SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 4 YEARS AND (FIRST_DATE - 1 YEAR))
	AND HIGH_RISK = 0 	
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('*','{redacted}','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1',
					'NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','>130')
	AND UNITOFMEASUREMENT <> '%'


UNION 

SELECT
	W.ALF_PE,
	FIRST_DATE AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(VAL AS DECIMAL(31,8)) AS EVENT_VAL,
	UNITOFMEASUREMENT
FROM 
	SAIL1483V.WRRS_OBSERVATION_RESULT_20240605 W

JOIN (SELECT DISTINCT ALF_PE FROM SAILW1483V.EXTRACT_P4_WLGP_GP_EVENT_CLEANSED) G
ON W.ALF_PE = G.ALF_PE

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('HbA1c%')
	AND (SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 4 YEARS AND (FIRST_DATE - 1 YEAR))
	AND HIGH_RISK = 0 
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('*','{redacted}','NA (Haemolysed specimen)','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1',
	'NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13')
)
,

HBA1C AS
(
SELECT
E.ALF_PE,
FIRST_DATE,
EVENT_VAL,
NULL AS EVENT_VAL_2,
'HbA1c' AS TYPE
FROM
(
SELECT
ALF_PE,
MAX(EVENT_VAL) AS EVENT_VAL
FROM
(
SELECT
ALF_PE,
EVENT_VAL
FROM HBA1C_READ

UNION

SELECT
ALF_PE,
EVENT_VAL 
FROM WRRS_HBA1C
)
GROUP BY ALF_PE
) E

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M
ON E.ALF_PE = M.ALF_PE
)
,

GP_EGFR AS
(
SELECT
ALF_PE,
MAX(RENAL_BEFORE) AS RENAL_BEFORE
FROM
(
SELECT
GP.ALF_PE,
CASE WHEN EVENT_VAL < 60 THEN 1 ELSE 0 END AS RENAL_BEFORE
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

JOIN GP_DATA GP
ON M.ALF_PE = GP.ALF_PE

JOIN SAILUKHDV.READ_CD_CV2_SCD R
ON GP.EVENT_CD = R.READ_CODE

WHERE (R.PREF_TERM_30 LIKE('%eGFR%') OR R.PREF_TERM_30 LIKE('%Glom%'))
		AND (EVENT_DT BETWEEN M.FIRST_DATE - 4 YEARS AND (M.FIRST_DATE - 1 YEAR))
		AND EVENT_VAL IS NOT NULL
		AND HIGH_RISK = 0 
		AND EVENT_VAL > 0	
)
GROUP BY ALF_PE
)
,

WRRS_EGFR AS
(
SELECT
ALF_PE,
MAX(RENAL_BEFORE) AS RENAL_BEFORE
FROM
(
SELECT
ALF_PE, 
CASE WHEN VAL < 60 THEN 1 ELSE 0 END AS RENAL_BEFORE
FROM
(
SELECT
	W.ALF_PE,
	FIRST_DATE AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL END
	AS INTEGER) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAILW1483V.EXTRACT_WRRS_OBSERVATION_RESULT W

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND (SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 4 YEARS AND (FIRST_DATE - 1 YEAR))
	AND HIGH_RISK = 0 
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('*','{redacted}','NA (Haemolysed specimen)','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1',
	'NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13')
)

UNION 

SELECT
ALF_PE, 
CASE WHEN VAL < 60 THEN 1 ELSE 0 END AS RENAL_BEFORE
FROM
(
SELECT
	W.ALF_PE,
	FIRST_DATE AS DIAG,
	SPCM_COLLECTED_DT AS TEST,
	VAL_TYPE,
	CODE,	
	NAME,	
	READ_CD,
	CAST(
	CASE 
		WHEN VAL = '>90' THEN 91
		WHEN VAL = '>60' THEN 61
		ELSE VAL END
	AS INTEGER) AS VAL,	
	UNITOFMEASUREMENT
FROM 
	SAIL1483V.WRRS_OBSERVATION_RESULT_20240605 W

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT F
ON W.ALF_PE = F.ALF_PE
	
WHERE NAME LIKE('%GFR%')
	AND (SPCM_COLLECTED_DT BETWEEN FIRST_DATE - 4 YEARS AND (FIRST_DATE - 1 YEAR))
	AND HIGH_RISK = 0 
	AND VAL IS NOT NULL
	AND VAL_TYPE = 'SN'
	AND VAL NOT IN('*','{redacted}','NA (Haemolysed specimen)','Serum Haemolysed','Not available.','NA (No sample)','NA','Insufficient sample','<0.1',
	'NA (TEST NOT PERFORMED.)','NA (Insufficient)','>165','<20','Not Tested','<18','<15','Not Available','>3270.8','<13')
)
)
GROUP BY ALF_PE
)
,

EGFR AS
(
SELECT
E.ALF_PE,
FIRST_DATE,
EVENT_VAL,
NULL AS EVENT_VAL_2,
'eGFR' AS TYPE
FROM
(
SELECT
ALF_PE,
MAX(RENAL_BEFORE) AS EVENT_VAL
FROM
(
SELECT
ALF_PE,
RENAL_BEFORE
FROM GP_EGFR

UNION

SELECT
ALF_PE,
RENAL_BEFORE 
FROM WRRS_EGFR
)
GROUP BY ALF_PE
) E

JOIN SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M
ON E.ALF_PE = M.ALF_PE
)
,

BP_READ AS
(
SELECT
ALF_PE,
FIRST_DATE,
SYS AS EVENT_VAL,
DYS AS EVENT_VAL_2,
'BP' AS TYPE
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY SYS,DYS DESC) AS RANK
FROM
(
SELECT
	M.ALF_PE,
	FIRST_DATE,
	EVENT_DT,
	SYS,
	DYS
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

JOIN SAILW1483V.ALL_CLEANED_BLOOD_PRESSURES BP
ON M.ALF_PE = BP.ALF_PE
	
WHERE 
	(BP.EVENT_DT BETWEEN M.FIRST_DATE - 4 YEARS AND (M.FIRST_DATE - 1 YEAR))
	AND HIGH_RISK = 0 
	AND SYS > 0
	AND DYS > 0
)
)
WHERE RANK = 1
)
,

UNION AS
(
SELECT
*
FROM HBA1C

UNION

SELECT
*
FROM EGFR

UNION

SELECT
*
FROM BP_READ
)

SELECT
ALF_PE,
FIRST_DATE,
TYPE,
CASE 
	WHEN TYPE = 'HbA1c' AND EVENT_VAL >= 48 THEN 1 
	WHEN TYPE = 'eGFR' AND EVENT_VAL = 1 THEN 1 
	WHEN TYPE = 'BP' AND (EVENT_VAL >= 140 OR EVENT_VAL_2 >= 90) THEN 1 
	ELSE 0 
END AS HIGH
FROM UNION
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.TEMP_RISK_READINGS_3YR
;
-----------------------------------------------------------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_HIGH_RISK_READINGS_ANY_3YR');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_HIGH_RISK_READINGS_ANY_3YR
(
	YEAR		INTEGER,
	CAT			VARCHAR(10),
	COUNT		INTEGER
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table

INSERT INTO SAILW1483V.TEMP_HIGH_RISK_READINGS_ANY_3YR

WITH A AS
(
SELECT 
	ALF_PE,
	YEAR(FIRST_DATE) AS YEAR,
	MAX(HIGH) AS HIGH
FROM 
	SAILW1483V.TEMP_RISK_READINGS_3YR
GROUP BY ALF_PE,FIRST_DATE
)
,

GROUP AS
(
SELECT
YEAR,
SUM(HIGH) AS HIGH,
COUNT(ALF_PE) AS COUNT
FROM A

GROUP BY YEAR
ORDER BY YEAR
)
,

PROP AS
(
SELECT
G.YEAR,
G.HIGH,
G.COUNT - G.HIGH AS TEST,
T.TOTAL - (G.COUNT) AS NO_TEST,
T.TOTAL
FROM GROUP G

JOIN
(
SELECT
YEAR(FIRST_DATE) AS YEAR,
COUNT(DISTINCT ALF_PE) AS TOTAL
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT

WHERE HIGH_RISK = 0

GROUP BY YEAR(FIRST_DATE)
ORDER BY YEAR(FIRST_DATE)
) T
ON G.YEAR = T.YEAR
)

SELECT
YEAR,
'HIGH' AS CAT,
HIGH AS COUNT
FROM PROP

UNION 

SELECT
YEAR,
'TEST' AS CAT,
TEST AS COUNT
FROM PROP

UNION 

SELECT
YEAR,
'NO TEST' AS CAT,
NO_TEST AS COUNT
FROM PROP
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.TEMP_HIGH_RISK_READINGS_ANY_3YR
;
-----------------------------------------------------------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.TEMP_HIGH_RISK_READINGS_3YR');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.TEMP_HIGH_RISK_READINGS_3YR
(
	YEAR		INTEGER,
	TYPE		VARCHAR(30),
	CAT			VARCHAR(10),
	COUNT		INTEGER
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table

INSERT INTO SAILW1483V.TEMP_HIGH_RISK_READINGS_3YR

WITH GROUP AS
(
SELECT
YEAR(FIRST_DATE) AS YEAR,
TYPE,
SUM(HIGH) AS HIGH,
COUNT(ALF_PE) AS COUNT
FROM SAILW1483V.TEMP_RISK_READINGS_3YR

GROUP BY YEAR(FIRST_DATE), TYPE
ORDER BY YEAR(FIRST_DATE)
)
,

PROP AS
(
SELECT
G.YEAR,
G.TYPE,
G.HIGH,
G.COUNT - G.HIGH AS TEST,
T.TOTAL - (G.COUNT) AS NO_TEST,
T.TOTAL
FROM GROUP G

JOIN
(
SELECT
YEAR(FIRST_DATE) AS YEAR,
COUNT(DISTINCT ALF_PE) AS TOTAL
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT

WHERE HIGH_RISK = 0

GROUP BY YEAR(FIRST_DATE)
ORDER BY YEAR(FIRST_DATE)
) T
ON G.YEAR = T.YEAR

ORDER BY G.YEAR
)

SELECT
YEAR,
TYPE,
'HIGH' AS CAT,
HIGH AS COUNT
FROM PROP

UNION 

SELECT
YEAR,
TYPE,
'TEST' AS CAT,
TEST AS COUNT
FROM PROP

UNION 

SELECT
YEAR,
TYPE,
'NO TEST' AS CAT,
NO_TEST AS COUNT
FROM PROP
;
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.TEMP_HIGH_RISK_READINGS_3YR;
