
--Box 1
SELECT 
COUNT(DISTINCT ALF_PE) 
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT;

--Box 3
SELECT 
COUNT(DISTINCT ALF_PE) 
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT 
WHERE AGE_DIAG < 85;

--Box 5
SELECT 
COUNT(DISTINCT M.ALF_PE) 
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

LEFT JOIN 
(SELECT * FROM SAILW1483V.TEMP_INC_LLT_PRIOR_COMB WHERE LLT <> 'NOTX') L
ON M.ALF_PE = L.ALF_PE

WHERE AGE_DIAG < 85 
AND L.ALF_PE IS NULL;

--Box 7
SELECT 
COUNT(DISTINCT M.ALF_PE) 
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

LEFT JOIN 
(SELECT * FROM SAILW1483V.TEMP_INC_LLT_PRIOR_COMB WHERE LLT <> 'NOTX') L
ON M.ALF_PE = L.ALF_PE

WHERE AGE_DIAG < 85 
AND L.ALF_PE IS NULL 
AND M.RENAL_BEFORE = 0;

--Box 9
SELECT 
COUNT(DISTINCT M.ALF_PE) 
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

LEFT JOIN 
(SELECT * FROM SAILW1483V.TEMP_INC_LLT_PRIOR_COMB WHERE LLT <> 'NOTX') L
ON M.ALF_PE = L.ALF_PE

WHERE AGE_DIAG < 85 
AND L.ALF_PE IS NULL 
AND M.RENAL_BEFORE = 0
AND YEAR(M.FIRST_DATE) >= 2014;


--Box 9
WITH A AS
(
SELECT 
M.ALF_PE
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT M

LEFT JOIN 
(SELECT * FROM SAILW1483V.TEMP_INC_LLT_PRIOR_COMB WHERE LLT <> 'NOTX') L
ON M.ALF_PE = L.ALF_PE

WHERE AGE_DIAG < 85 
AND L.ALF_PE IS NULL 
AND M.RENAL_BEFORE = 0
AND YEAR(M.FIRST_DATE) >= 2014
)

SELECT
COUNT(DISTINCT ALF_PE),
QRISK_FLAG
FROM
(
SELECT 
A.*,
CASE WHEN QRISK_VAL <> 'NOT' THEN 1 ELSE 0 END AS QRISK_FLAG
FROM A

LEFT JOIN SAILW1483V.TEMP_QRISK_PRIOR_COMB_MAX Q
USING(ALF_PE)
)
GROUP BY QRISK_FLAG
;
