
--Box 1

CALL FNC.DROP_IF_EXISTS ('SAILW1483V.PREP_GP_ALF_PEDW');
COMMIT;


CREATE TABLE SAILW1483V.PREP_GP_ALF_PEDW
(
ALF_PE BIGINT
)
DISTRIBUTE BY HASH(ALF_PE);
COMMIT;


INSERT INTO SAILW1483V.PREP_GP_ALF_PEDW
SELECT
	DISTINCT ALF_PE
FROM SAILW1483V.GP_DATA GP
WHERE GP.EVENT_DT BETWEEN SAILW1483V.START_DATE AND SAILW1483V.END_DATE

UNION

SELECT
	DISTINCT ALF_PE
FROM SAILW1483V.PEDW_SPELL_DATA SPELL
WHERE SPELL.ADMIS_DT BETWEEN SAILW1483V.START_DATE AND SAILW1483V.END_DATE
;
COMMIT;

--------

CALL FNC.DROP_IF_EXISTS ('SAILW1483V.PREP_WDS_ALFS');
COMMIT;


CREATE TABLE SAILW1483V.PREP_WDS_ALFS
(
ALF_PE BIGINT
)
DISTRIBUTE BY HASH(ALF_PE);
COMMIT;


INSERT INTO SAILW1483V.PREP_WDS_ALFS
SELECT 
	DISTINCT ALF_PE
FROM SAILW1483V.WDSD_DATA W
WHERE W.ACTIVEFROM BETWEEN SAILW1483V.START_DATE AND SAILW1483V.END_DATE
OR W.ACTIVETO BETWEEN SAILW1483V.START_DATE AND SAILW1483V.END_DATE
OR (W.ACTIVETO IS NULL AND W.ACTIVEFROM < SAILW1483V.START_DATE)
;
COMMIT;

--------

SELECT
	COUNT(DISTINCT A.ALF_PE)
FROM 
	SAILW1483V.PREP_WDS_ALFS A;


------------------------------------------   
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PREP_ALF_PEDW_TYPES');
COMMIT;
------------------------------------------
--
--Create Table
--
CREATE TABLE SAILW1483V.PREP_ALF_PEDW_TYPES
(
	ALF_PE		BIGINT,
	TYPE		VARCHAR(10),
	CODE		VARCHAR(10),
	DESC 		VARCHAR(100),
	EVENT_DT	DATE
)
;
COMMIT;
--
------------------------------------------
--
INSERT INTO SAILW1483V.PREP_ALF_PEDW_TYPES
--
-- Returning ALFs from PEDW with an ASCVD diagnosis between 2000-2023
--
WITH A AS
(
SELECT
DIAG.PROV_UNIT_CD,
DIAG.SPELL_NUM_PE,
DIAG.EPI_NUM,
ICD_TYPE,
ICD.DIAG_CD_123,
ICD.DIAG_DESC_4 
FROM SAILW1483V.EXTRACT_PEDW_DIAG DIAG

JOIN SAILW1483V.PHEN_ASCVD_ICD10 ICD
ON DIAG.DIAG_CD_123  = ICD.DIAG_CD_123 
)
,

B AS
(
SELECT
EPI.PROV_UNIT_CD,
EPI.SPELL_NUM_PE,
ICD_TYPE,
A.DIAG_CD_123,
A.DIAG_DESC_4
FROM A 

JOIN SAILW1483V.EXTRACT_PEDW_EPISODE EPI
ON A.PROV_UNIT_CD = EPI.PROV_UNIT_CD
AND A.SPELL_NUM_PE = EPI.SPELL_NUM_PE
AND A.EPI_NUM = EPI.EPI_NUM
)
,

C AS
(
SELECT
SPELL.ALF_PE,
ICD_TYPE AS TYPE,
DIAG_CD_123 AS CODE,
DIAG_DESC_4 AS DESC,
SPELL.ADMIS_DT AS EVENT_DT
FROM B

JOIN SAILW1483V.EXTRACT_PEDW_SPELL SPELL
ON B.PROV_UNIT_CD = SPELL.PROV_UNIT_CD
AND B.SPELL_NUM_PE = SPELL.SPELL_NUM_PE
)
,

D AS
(
SELECT
*
FROM C

WHERE C.EVENT_DT BETWEEN SAILW1483V.START_DATE AND SAILW1483V.END_DATE	
)
,

E AS
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_DT) AS RANK
FROM D
)

SELECT
ALF_PE,
TYPE,
CODE,
DESC,
EVENT_DT
FROM E

WHERE RANK = 1
;
COMMIT;
-------------------------------------   
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PREP_ALF_WLGP_TYPES');
COMMIT;
------------------------------------------
--
--Create Table
CREATE TABLE SAILW1483V.PREP_ALF_WLGP_TYPES
(
	ALF_PE		BIGINT,
	TYPE		VARCHAR(10),
	CODE		VARCHAR(10),
	DESC 		VARCHAR(200),	
	EVENT_DT	DATE
)
;
COMMIT;
------------------------------------------
--
--Insert into Table
--
INSERT INTO SAILW1483V.PREP_ALF_WLGP_TYPES
(
--
-- Returning ALFs from WLGP with an ASCVD diagnosis between 2000-2023
--
SELECT
ALF_PE,
TYPE,
CODE,
DESC,
EVENT_DT
FROM
(
SELECT
	GP.ALF_PE,
	READ_TYPE AS TYPE,
	READ_CODE AS CODE,
	C.DESC,
	EVENT_DT,
	ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY EVENT_DT) AS RANK
FROM 
	SAILW1483V.EXTRACT_WLGP_GP_EVENT_CLEANSED GP

JOIN SAILW1483V.PHEN_ASCVD_READ C
	ON GP.EVENT_CD = C.READ_CODE
	
WHERE 
	GP.EVENT_DT BETWEEN SAILW1483V.START_DATE AND SAILW1483V.END_DATE
)
WHERE RANK = 1
);
COMMIT;
--
------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PREP_ALF_TOP_CONSORT_TYPES');
COMMIT;
------------------------------------------
--
--Create Table
CREATE TABLE SAILW1483V.PREP_ALF_TOP_CONSORT_TYPES
(
	ALF_PE		BIGINT,
	CODE		VARCHAR(10),
	DESC 		VARCHAR(200),		
	TYPE		VARCHAR(10)
)
;
COMMIT;
------------------------------------------
--
--Insert into Table
--
INSERT INTO SAILW1483V.PREP_ALF_TOP_CONSORT_TYPES
--
-- Checking ALFs with ASCVD diagnoses from PEDW & WLGP have a record in WDSD
--
WITH GP_PEDW AS
(
SELECT
	*
FROM SAILW1483V.PREP_ALF_WLGP_TYPES

UNION

SELECT
	*
FROM SAILW1483V.PREP_ALF_PEDW_TYPES
)

SELECT
ALF_PE,
CODE,
DESC,
TYPE
FROM
(
SELECT 
	GP_PEDW.ALF_PE,
	TYPE,
	CODE,
	DESC,
	ROW_NUMBER() OVER(PARTITION BY GP_PEDW.ALF_PE ORDER BY EVENT_DT) AS RANK
FROM GP_PEDW

JOIN SAILW1483V.PREP_ALF_WDSD WDS
ON GP_PEDW.ALF_PE = WDS.ALF_PE
)
WHERE RANK = 1
;
COMMIT;
--
------------------------------------------

--Box 2

WITH BOX_2 AS
(
SELECT
	DISTINCT A.ALF_PE
FROM 
	SAILW1483V.PREP_WDS_ALFS A
)

SELECT 
	COUNT(DISTINCT BOX_2.ALF_PE)
FROM
	BOX_2
	
LEFT JOIN 
(
SELECT DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_ALF_TOP_CONSORT

UNION

SELECT DISTINCT ALF_PE
FROM SAILW1483V.PREP_ALF_TOP_CONSORT_TYPES
WHERE TYPE <> 'PAD'
) A
ON BOX_2.ALF_PE = A.ALF_PE

WHERE A.ALF_PE IS NULL;

--------------------------------------------------

--Box 3

SELECT 
	COUNT(DISTINCT ALF_PE)
FROM
(
SELECT DISTINCT ALF_PE
FROM  SAILW1483V.PRIOR_CVD_DEATH_ALF_TOP_CONSORT

UNION

SELECT DISTINCT ALF_PE
FROM SAILW1483V.PREP_ALF_TOP_CONSORT_TYPES 
WHERE TYPE <> 'PAD'
);

--------------------------------------------------

--Box 4

WITH A AS
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.COHORT_MASTER_FINAL
WHERE TYPE <> 'PAD'
)
,

B AS
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_ALF_TOP_CONSORT

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PREP_ALF_TOP_CONSORT_TYPES
WHERE TYPE <> 'PAD'
)


SELECT 
COUNT(DISTINCT B.ALF_PE)
FROM B

LEFT JOIN A
ON A.ALF_PE = B.ALF_PE 

WHERE A.ALF_PE IS NULL
;

--------------------------------------------------

SELECT 
COUNT(DISTINCT ALF_PE)
FROM
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.COHORT_MASTER_FINAL
WHERE TYPE <> 'PAD'
)
;

--------------------------------------------------


WITH A AS
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.COHORT_MASTER_FINAL
WHERE TYPE <> 'PAD'
)
,

B AS
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS
WHERE YEAR(DEATH_DT) >= 2010

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.COHORT_MASTER_FINAL
WHERE FIRST_YEAR >= 2010
AND TYPE <> 'PAD'
)

SELECT
COUNT(DISTINCT A.ALF_PE)
FROM A

LEFT JOIN B
ON B.ALF_PE = A.ALF_PE

WHERE B.ALF_PE IS NULL

;

--------------------------------------------------

SELECT
COUNT(DISTINCT ALF_PE)
FROM
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS
WHERE YEAR(DEATH_DT) >= 2010

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.COHORT_MASTER_FINAL
WHERE FIRST_YEAR >= 2010
AND TYPE <> 'PAD'
)
;


--------------------------------------------------

WITH A AS
(
SELECT 
ALF_PE,
TYPE
FROM
(
SELECT
ALF_PE,
TYPE,
ROW_NUMBER() OVER(PARTITION BY ALF_PE ORDER BY FIRST_DATE) AS RANK
FROM
(
SELECT 
DISTINCT ALF_PE,
CASE 
WHEN TYPE = 'IHD' THEN 'DEATH IHD' 
WHEN TYPE = 'ST' THEN 'DEATH ST' 
ELSE NULL
END AS TYPE,
DEATH_DT AS FIRST_DATE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS
WHERE YEAR(DEATH_DT) >= 2010

UNION 

SELECT 
DISTINCT ALF_PE,
TYPE,
FIRST_DATE
FROM SAILW1483V.COHORT_MASTER_FINAL
WHERE FIRST_YEAR >= 2010
AND TYPE <> 'PAD'
)
)
WHERE RANK = 1
)
,

ALL AS
(
SELECT
COUNT(DISTINCT ALF_PE) AS TOTAL
FROM A
)
,

SPLIT AS
(
SELECT
TYPE,
COUNT(DISTINCT ALF_PE) AS FREQ
FROM A

GROUP BY TYPE
)

SELECT
A.*,
ROUND(FREQ / CAST(ALL.TOTAL AS DECIMAL(31,8)),3)*100 AS PCT
FROM SPLIT A

CROSS JOIN ALL
;


--------------------------------------------------

WITH A AS
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_ALFS
WHERE YEAR(DEATH_DT) >= 2010

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.COHORT_MASTER_FINAL
WHERE FIRST_YEAR >= 2010
AND TYPE <> 'PAD'
)
,

B AS
(
SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_CVD_DEATH_COHORT_MASTER
WHERE YEAR(DEATH_DT) >= 2010

UNION 

SELECT 
DISTINCT ALF_PE
FROM SAILW1483V.PRIOR_COHORT_HE_MASTER
WHERE FIRST_YEAR >= 2010
)

SELECT
COUNT(DISTINCT A.ALF_PE)
FROM A

LEFT JOIN B
ON A.ALF_PE = B.ALF_PE

WHERE B.ALF_PE IS NULL
;

---------------------------------------


SELECT
COUNT(DISTINCT ALF_PE)
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT;



---------------------------------------

WITH A AS
(
SELECT 
ALF_PE, 
TYPE 
FROM SAILW1483V.PRIOR_COMB_COHORT_MASTER_LLT
)
,

ALL AS
(
SELECT
COUNT(DISTINCT ALF_PE) AS TOTAL
FROM A
)
,

SPLIT AS
(
SELECT
TYPE,
COUNT(DISTINCT ALF_PE) AS FREQ
FROM A

GROUP BY TYPE
)

SELECT
A.*,
ROUND(FREQ / CAST(ALL.TOTAL AS DECIMAL(31,8)),3)*100 AS PCT
FROM SPLIT A

CROSS JOIN ALL
;

